--- Add to ox_inventory/data/items.lua - Adjust weights if necessary!
--- Let's Cook Ingredients:
	['lclobstertails'] 		    = { label = 'Frozen Lobster Tails', 		weight = 80,    stack = true,   close = true,   description = '', },
	['lcbutter'] 	            = { label = 'Stick of Butter', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcpbutter'] 		        = { label = 'Peanut Butter', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lclemon'] 		        = { label = 'Fresh Lemon', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcbeefpatty'] 		    = { label = 'Raw Beef Patty', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcburgerbun'] 			= { label = 'Burger Bun', 				    weight = 80,    stack = true,   close = true,   description = '', },
	['lccheese'] 			    = { label = 'Cheddar Cheese', 				weight = 80,    stack = true,   close = true,   description = '', },
	['lcsausage'] 		        = { label = 'Sausage Pack', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcbread'] 		        = { label = 'Fresh Bread', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcveggiepack'] 	        = { label = 'Fresh Veggies', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcdryrice'] 	            = { label = 'Bag of Rice', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcmaccheese'] 		    = { label = 'Frozen Mac N Cheese', 			weight = 80,    stack = true,   close = true,   description = '', },
	['lcpancakes'] 	            = { label = 'Frozen Pancakes', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcsyrup'] 	            = { label = 'Pancake Syrup', 	            weight = 80,    stack = true,   close = true,   description = '', },
	['lcramenpack'] 		    = { label = 'Ramen Pack', 	                weight = 80,    stack = true,   close = true,   description = '', },
	['lcfrozenpizza']	 	    = { label = 'Frozen Pizza', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcgrapes'] 	            = { label = 'Fresh Grapes', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcsugar'] 		        = { label = 'Sugar', 		                weight = 80,    stack = true,   close = true,   description = '', },
	['lcapple'] 		        = { label = 'Fresh Apple', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcorange'] 		        = { label = 'Fresh Orange', 	            weight = 80,    stack = true,   close = true,   description = '', },
	['lcbanana'] 		        = { label = 'Ripe Banana', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcicecubes'] 		        = { label = 'Cubed Ice', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcmilk'] 		            = { label = 'Milk Carton', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcstrawberry'] 	        = { label = 'Fresh Strawberry', 		    weight = 80,    stack = true,   close = true,   description = '', },
	['lcteabag'] 		        = { label = 'Tea Bag', 	                    weight = 80,    stack = true,   close = true,   description = '', },
	['lccoffeepod'] 		    = { label = 'Coffee Pod', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcgteapod'] 		        = { label = 'Green Tea Pod', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawribs'] 		        = { label = 'Raw Pork Ribs', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcbbqsauce'] 			    = { label = 'BBQ Sauce', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawchicken'] 		    = { label = 'Raw Leg Quarter', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawbeef'] 		        = { label = 'Raw Steak Beef', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lccorncob'] 		        = { label = 'Ear of Corn', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcptartpk'] 	            = { label = 'Poptart Pack', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcicing']		            = { label = 'Poptart Icing', 			    weight = 80,    stack = true,   close = true,   description = '', },
    ['lcfrozewaff'] 		    = { label = 'Frozen Waffles', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lchamslice'] 		        = { label = 'Slice of Ham', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcflour'] 			    = { label = 'Bag of Flour', 				weight = 80,    stack = true,   close = true,   description = '', },
	['lcvegoil'] 			    = { label = 'Vegetable Oil', 				weight = 80,    stack = true,   close = true,   description = '', },
	['lccheestkpk'] 		    = { label = 'Frozen Cheesesticks', 			weight = 80,    stack = true,   close = true,   description = '', },
	['lcmarinara'] 		        = { label = 'Marinara Sauce', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['lcpotato'] 	            = { label = 'Fresh Potatos', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawchops'] 	            = { label = 'Raw Lamb Chops', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawfish'] 		        = { label = 'Raw Fish', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawsalmon'] 	        = { label = 'Raw Salmon', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcbeefstrips'] 	        = { label = 'Raw Beef Strip', 	            weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawbreast'] 		    = { label = 'Raw Chicken Breast', 	        weight = 80,    stack = true,   close = true,   description = '', },
	['lccocoapod']	 	        = { label = 'Cocoa Pod', 			        weight = 80,    stack = true,   close = true,   description = '', },
	['lcvaniwafers'] 	        = { label = 'Vanilla Wafers', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcpudding'] 		        = { label = 'Vanilla Pudding', 		        weight = 80,    stack = true,   close = true,   description = '', },
	['lcseasoning'] 		    = { label = 'Seasonings', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcrawoxtail'] 		    = { label = 'Raw Ox Tails', 	            weight = 80,    stack = true,   close = true,   description = '', },
	['lccreamer'] 		        = { label = 'Coffee Cream', 			    weight = 80,    stack = true,   close = true,   description = '', },
	['water_jug'] 		        = { label = 'Water Jug', 			    	weight = 80,    stack = true,   close = true,   description = '', },
    ['lcjelly'] 		        = { label = 'Grape Jelly', 			        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcegg'] 		            = { label = 'Fresh Egg', 			        weight = 80,    stack = true,   close = true,   description = '', },
    ['lccanbeans'] 		        = { label = 'Canned Beans', 			    weight = 80,    stack = true,   close = true,   description = '', },
    ['lccansoup'] 		        = { label = 'Canned Soup', 			        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcglassjar'] 		        = { label = 'Glass Jar', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcaluminum'] 		        = { label = 'Metal Parts', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsteelcan'] 		        = { label = 'Steel Can', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcstyrofoam'] 		    = { label = 'Styrofoam', 		            weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_melon'] 		    = { label = 'Melon', 		        		weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_coffebean'] 		= { label = 'Coffee Bean', 		        	weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_strawberry'] 	= { label = 'Strawberry', 		        	weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_sugar'] 		    = { label = 'Brown Sugar', 		        	weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_corn'] 		    = { label = 'Corn', 		        		weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_yeast'] 		    = { label = 'Yeast', 		        		weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_blkberry'] 		= { label = 'Blackberry', 		        	weight = 80,    stack = true,   close = true,   description = '', },
	['lcmshine_mash'] 		    = { label = 'Mash', 		        		weight = 80,    stack = true,   close = true,   description = '', },
    ['lccanpeas']               = { label = 'Canned Peas', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcpeppers']               = { label = 'Fresh Peppers', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcrawshrimp']             = { label = 'Raw Shrimp', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcrawgoat']               = { label = 'Goat Meat', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcplantain']              = { label = 'Plantain', 		            weight = 80,    stack = true,   close = true,   description = '', },

 
    -- Let's Cook! Edible Items:
    ['lclemonlobster'] 			= { label = 'Lemony Lobster Tails', 	    weight = 80,    stack = true,   close = true,   description = '', },
    ['lccheeseburger'] 			= { label = 'Cheese Burger', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsausagedog'] 			= { label = 'Sausage Dog', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcgumbo'] 			    = { label = 'Gumbo', 	                    weight = 80,    stack = true,   close = true,   description = '', },
    ['lcoxtails'] 			    = { label = 'Oxtails n Rice', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcmaccheesy'] 			= { label = 'Mac n Cheesy', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lchotcakes'] 			    = { label = 'Hot Cakes', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcricebowl'] 			    = { label = 'Rice Bowl', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcramennoodle'] 			= { label = 'Ramen Noodles', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcquickpizza'] 			= { label = 'Pepperoni Pizza', 	            weight = 80,    stack = true,   close = true,   description = '', }, 
    ['lcribs'] 			        = { label = 'BBQ Ribs', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lclegquarter'] 			= { label = 'BBQ Chicken', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsteak'] 			    = { label = 'Grilled Steak', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcgrillcorn'] 			= { label = 'Grilled Corn', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcgrillveggies'] 			= { label = 'Grilled Veggies', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lctoast'] 			    = { label = 'Toasted PB & J', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcpoptart'] 			    = { label = 'Iced Poptart', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcwaffle'] 			    = { label = 'Insta Waffle', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lctoasti'] 			    = { label = 'Cheese Toasti', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lchamtoastie'] 			= { label = 'Ham Toasti', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcfriedchicken'] 			= { label = 'Fried Chicken', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lccheesesticks'] 			= { label = 'Cheese Sticks', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcfrenchfries'] 			= { label = 'Home Fries', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lclambchops'] 			= { label = 'Fried Chops', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcfriedfish'] 			= { label = 'Fried Fish', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsalmon'] 			    = { label = 'Seered Salmon', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcbstirfry'] 			    = { label = 'Beef Stir Fry', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcchickensand'] 			= { label = 'Chicken Sandwich', 	        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcbffriedrice'] 			= { label = 'Beef Fried Rice', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcckfriedrice'] 			= { label = 'Chicken Fried Rice', 	        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcapplesauce'] 			= { label = 'Apple Sauce', 	                weight = 80,    stack = true,   close = true,   description = '', },
    ['lcnanacream'] 			= { label = 'Banana Split', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcberrycream'] 			= { label = 'Strawberry Icecream', 	        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcchoccream'] 			= { label = 'Chocolate Icecream', 	        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcbpudding'] 			    = { label = 'Banana Pudding', 	            weight = 80,    stack = true,   close = true,   description = '', },
    ['lceggsandwich'] 		    = { label = 'Egg Sandwich', 			    weight = 80,    stack = true,   close = true,   description = '', },
    ['lcbakedbeans'] 		    = { label = 'Baked Beans', 			        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsoupbowl'] 		        = { label = 'Soup', 			            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcpepshrimp']             = { label = 'Pepper Shrimp Plantain', 	    weight = 80,    stack = true,   close = true,   description = '', },
    ['lccurrgoat']              = { label = 'Curry Goat Bowl', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcricepeas']              = { label = 'Rice Peas Bowl', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcyellrice']              = { label = 'Yellow Rice Bowl', 		    weight = 80,    stack = true,   close = true,   description = '', },

    -- Let's Cook! Drinkable Items:
    ['lcgrapejuice']            = { label = 'Grape Juice', 				    weight = 80,    stack = true,   close = true,   description = '', },
    ['lcapplejuice']            = { label = 'Apple Juice', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcorangejuice']           = { label = 'Orange Juice', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcnanasmoothie']          = { label = 'Banana Smoothie', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lcberrysmoothie']         = { label = 'Berry Smoothie', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lccuptea']                = { label = 'Glass of Tea', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lccupcoffee']             = { label = 'Cup of Coffee', 		        weight = 80,    stack = true,   close = true,   description = '', },
    ['lchotcocoa']              = { label = 'Hot Cocoa', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lcgreentea']              = { label = 'Green Tea', 		            weight = 80,    stack = true,   close = true,   description = '', },
    ['lccappucino']             = { label = 'Cappucino Expresso', 		    weight = 80,    stack = true,   close = true,   description = '', },
	['lcwhite_lighting']        = { label = 'White Lightnin Moonshine', 	weight = 80,    stack = true,   close = true,   description = '', },
    ['lcsour_watermelon']       = { label = 'Sour Watermelon Moonshine', 	weight = 80,    stack = true,   close = true,   description = '', },
    ['lcmountain_java']         = { label = 'Mountain Java Moonshine', 		weight = 80,    stack = true,   close = true,   description = '', },
    ['lcstrawberry_shine']      = { label = 'Strawberry Moonshine', 		weight = 80,    stack = true,   close = true,   description = '', },
    ['lcblkberry_shine']        = { label = 'Blackberry Moonshine', 		weight = 80,    stack = true,   close = true,   description = '', },

    --- Let's Cook Props
    ['lc_hobo'] 		        = { label = 'Hobo Stove', 			        weight = 80,    stack = false,   close = true,   description = '', },
	['lc_grill'] 		        = { label = 'BBQ Grill', 			        weight = 80,    stack = false,   close = true,   description = '', },
	['lc_microwave'] 		    = { label = 'Microwave', 		            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_juicer'] 	            = { label = 'Juicer', 		                weight = 80,    stack = false,   close = true,   description = '', },
	['lc_coffee'] 		        = { label = 'Coffee Maker', 	            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_griddle'] 		        = { label = 'Griddle', 			            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_processor'] 		    = { label = 'Food Processor', 			    weight = 80,    stack = false,   close = true,   description = '', },
	['lc_toaster'] 		        = { label = 'Toaster', 			            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_fryer'] 			    = { label = 'Copper Pot', 		            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_table'] 		        = { label = 'Prep Table', 		            weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_printer'] 		        = { label = 'Printer', 		                weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_partybox'] 		    = { label = 'Party Box', 		            weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_stove'] 		        = { label = 'Stove', 		                weight = 80,    stack = false,   close = true,   description = '', },
	['lc_chair'] 		        = { label = 'Chair', 			            weight = 80,    stack = false,   close = true,   description = '', },
	['lc_gazebo'] 			    = { label = 'Gazebo', 		            	weight = 80,    stack = false,   close = true,   description = '', },
	['lc_still'] 		        = { label = 'Moonshine Still', 		        weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_weapbench'] 		    = { label = 'Weapons Bench', 		        weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_attabench'] 		    = { label = 'Attachments Bench', 		    weight = 80,    stack = false,   close = true,   description = '', },
    ['lc_ammobench'] 		    = { label = 'Ammo Bench', 		            weight = 80,    stack = false,   close = true,   description = '', },
