CREATE TABLE IF NOT EXISTS `mk_keyfobs` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`owner` VARCHAR(50) NULL DEFAULT NULL,
	`plate` VARCHAR(50) NULL DEFAULT NULL,
	`fakeplate` VARCHAR(50) NULL DEFAULT NULL,
	`model` VARCHAR(50) NULL DEFAULT NULL,
	`fobid` VARCHAR(50) NULL DEFAULT NULL,
	`old_fobs` LONGTEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `owner` (`owner`) USING BTREE,
	INDEX `plate` (`plate`) USING BTREE,
	INDEX `fobnumber` (`fobid`) USING BTREE,
	INDEX `Column 6` (`old_fobs`(1024)) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
