Config.Creation = {
    InteriorData = { --FOR MLO HOUSING
        price     = {minimum = 120000, maximum = 1545000},
        weight    = {minimum = 1000,   maximum = 10000},
        weedplant = {minimum = 0,      maximum = 50},
    },
    ShellData = { --FOR SHELL HOUSING
        price     = {minimum = 120000, maximum = 1545000},
        weight    = {minimum = 1000,   maximum = 10000},
        weedplant = {minimum = 0,      maximum = 50},
    },

    Shells = {
        ['Default Housing'] = { --any name
            'default_housing1_k4mb1', --shell name
            'default_housing2_k4mb1',
            'default_housing3_k4mb1',
            'default_housing4_k4mb1',
            'default_housing5_k4mb1',
            'default_housing6_k4mb1',
            'k4mb1_house1_shell',
            'k4mb1_house2_shell',
            'k4mb1_house3_shell',
            'k4mb1_house4_shell',
            'manor_housing1_k4mb1',
            'shell_frankaunt',
            'shell_medium2',
            'shell_medium3',
        },
        ['Deluxe Housing'] = {
            'deluxe_housing1_k4mb1',
            'deluxe_housing2_k4mb1',
            'deluxe_housing3_k4mb1',
            'luxury_housing1_k4mb1',
            'luxury_housing2_k4mb1',
            'luxury_housing3_k4mb1',
            'luxury_housing4_k4mb1',
            'shell_michael',
            'micheal_shell',
            'k4_mansion_shell',
            'k4_mansion2_shell',
            'k4_mansion3_shell',
        },
        ['Highend housing'] = {
            'highend_housing1_k4mb1',
            'highend_housing2_k4mb1',
            'highend_housing3_k4mb1',
            'shell_apartment1',
            'shell_apartment2',
            'shell_apartment3',
            'modern_housing1_k4mb1',
            'modern_housing2_k4mb1',
            'modern_housing3_k4mb1',
            'shell_ranch',
            'shell_highend',
            'shell_highendv2',
            'shell_westons',
            'shell_westons2',
            'playerhouse_tier1',
            'appartment',
        },
        ['Medium Housing'] = {
            'medium_housing1_k4mb1',
            'medium_housing2_k4mb1',
            'medium_housing3_k4mb1',
            'shell_v16mid',
            'shell_trevor',
            'shell_lester',
            'classichouse_shell',
            'classichouse2_shell',
            'classichouse3_shell',
            'trevors_shell',
            'frankelientje',
        },
        ['Lowend Housing'] = {
            'shell_v16low',
            'shell_trailer',
            'stashhouse1_shell',
            'stashhouse3_shell',
            'stashhouse_shell',
            'stashhouse2_shell',
        },
        ['Vinewood Housing'] = {
            'vinewood_housing1_k4mb1',
            'vinewood_housing2_k4mb1',
            'vinewood_housing3_k4mb1',
        },
        ['Basement Shell'] = {
            'k4mb1_basement1_shell',
            'k4mb1_basement2_shell',
            'k4mb1_basement3_shell',
            'k4mb1_basement5_shell',
        },
        ['Casino Hotel'] = {
            'k4mb1_casinohotel_shell',
        },
        ['Furnished house'] = {
            'kambi_furnishedhouse1',
            'furnitured_lowapart',
            'furnitured_midapart',
        },
        ['Motel'] = {
            'furnitured_motel',
            'k4_hotel1_shell',
            'k4_hotel2_shell',
            'k4_hotel3_shell',
            'k4_motel1_shell',
            'k4_motel2_shell',
            'k4_motel3_shell',
            'modernhotel2_shell',
            'modernhotel3_shell',
            'classicmotel_shell',
            'highendmotel_shell',
            'standardmotel_shell',
            'modernhotel_shell',
        },
        ['Random House'] = {
            'k4mb1_hoodhouse1_shell',
            'k4mb1_palhouse1_shell',
            'k4mb1_sandyhouse1_shell',
            'kambi_emptyhouse1',
            'kambi_emptyhouse1',
            'safehouse_k4mb1',
            'warehouse_k4mb1',
            'shell_warehouse2',
            'shell_warehouse3',
            'shell_warehouse1',
            'shell_warehouse1',
            'caravan_shell',
            'tante_shell',
        },
        ['Business'] = {
            'k4mb1_furnishedoffice1_shell',
            'k4mb1_furnishedoffice2_shell',
            'k4mb1_furnishedoffice3_shell',
            'k4mb1_furnishedoffice4_shell',
            'k4mb1_furnishedoffice5_shell',
            'k4mb1_laundry_shell',
            'gunworkshop_k4mb1',
            'k4coke_shell',
            'k4meth_shell',
            'k4weed_shell',
            'shell_coke1',
            'shell_coke2',
            'shell_meth',
            'shell_weed',
            'shell_weed2',
            'container_shell',
            'container2_shell',
            'shell_banham',
            'shell_office2',
            'shell_officebig',
            'shell_barber',
            'shell_gunstore',
            'shell_store2',
            'shell_store3',
            'shell_office1',
            'shell_store1',
        },
        ['Garage'] = {
            'new_garages1_k4mb1',
            'new_garages2_k4mb1',
            'new_garages3_k4mb1',
            'new_garages4_k4mb1',
            'shell_garagel',
            'shell_garages',
            'shell_garagem',
        },
    },

    CameraOptions = {
        lookSpeedX = 500.0,
        lookSpeedY = 500.0,
        moveSpeed = 10.0,
        climbSpeed = 10.0,
        rotateSpeed = 50.0,
    },
    
    ActionControls = {
        forward = {
            label = "Forward +/-",
            codes = {33, 32},
        },
        right = {
            label = "Right +/-",
            codes = {35, 34},
        },
        up = {
            label = "Up +/-",
            codes = {52, 51},
        },
        add_point = {
            label = "Add Point",
            codes = {24},
        },
        undo_point = {
            label = "Undo Last",
            codes = {25},
        },
        set_position = {
            label = "Set Position",
            codes = {24},
        },
        add_garage = {
            label = "Add Garage",
            codes = {24},
        },
        rotate_z = {
            label = "RotateZ +/-",
            codes = {20, 73},
        },
        rotate_z_scroll = {
            label = "RotateZ +/-",
            codes = {17, 16},
        },
        mod_z_shell = {
            label = "Z Axis +/-",
            codes = {180, 181},
        },
        mod_zoom_shell = {
            label = "Zoom +/-",
            codes = {180, 181},
        },
        increase_z = {
            label = "Z Boundary +/-",
            codes = {180, 181},
        },
        decrease_z = {
            label = "Z Boundary +/-",
            codes = {21, 180, 181},
        },
        change_shell = {
            label = "Next Shell Model",
            codes = {217},
        },
        done = {
            label = "Done",
            codes = {191},
        },
        back = {
            label = "Back",
            codes = {194},
        },
        change_player = {
            label = "Player +/-",
            codes = {82, 81},
        },
        select_player = {
            label = "Select Player",
            codes = {191},
        },
        enter = {
            label = "Select",
            codes = {191},
        },
        cancel = {
            label = "Cancel",
            codes = {194},
        },
        mouse1 = {
            label = "Set",
            codes = {24},
        },
    },
}
