INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('coke_bag', 'Bag of cocaine', 10),
	('coke', 'Cocaine', 1),
	('coke_leaf', 'Coca leaf', 1),
	('empty_bag', 'Empty bag', 1),
	('fertilizer', 'Fertilizer', 500),
	('ammonia', 'Ammonia', 100),
	('chemicals', 'Chemicals', 100),
	('meth_bag', 'Bag of meth', 10),
	('meth', 'Meth', 1),
	('weed_bag', 'Bag of weed', 10),
	('weed_seed', 'Weed seed', 5),
	('weed', 'Weed', 1),
	('weed_joint', 'Weed joint', 1),
	('weed_papers', 'Weed papers', 1),
	('trowel', 'Trowel', 200),
	('water_can', 'Watering can', 1000),
	('plastic_bag', 'Plastic bag', 1),
	('meth_table', 'Meth table', 5000),
	('poppy_plant', 'Poppy plant', 100),
	('heroin_bag', 'Bag of heroin', 1)
;