ALTER TABLE `users` DROP COLUMN IF EXISTS `is_dead`;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `is_dead` BOOLEAN NOT NULL DEFAULT 0 AFTER `status`;

ALTER TABLE `users` DROP COLUMN IF EXISTS `deaths`;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `deaths` int(255) NOT NULL DEFAULT 0 AFTER `is_dead`;