QBCore.Functions.CreateUseableItem('catfish', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('catfish', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('chicken_caesar_salad', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('chicken_caesar_salad', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crab_legs_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crab_legs_meal', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('glazed_salmon', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('glazed_salmon', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('gourmet_double_burger', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('gourmet_double_burger', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('shrimp_alfredo', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('shrimp_alfredo', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('steak_and_lobster_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('steak_and_lobster_meal', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('tilapia_fish_meal', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('tilapia_fish_meal', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('crab_cakes', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('crab_cakes', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('shrimp_and_crab_dip', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('shrimp_and_crab_dip', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('lobster_bisque', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('lobster_bisque', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('shells_clam_chowder', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('shells_clam_chowder', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('upeel_shrimp', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('upeel_shrimp', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('fried_mushrooms', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('fried_mushrooms', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('oysters_half_shell', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('oysters_half_shell', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('tropical_chicken_salad', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('tropical_chicken_salad', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('salmon_caesar_salad', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('salmon_caesar_salad', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('shrimp_pasta', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('shrimp_pasta', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('baby_lobster_pasta', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('baby_lobster_pasta', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)

QBCore.Functions.CreateUseableItem('fried_scallops', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('fried_scallops', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'hunger', 60)
    TriggerClientEvent('ak47_pearls:onEat', source)
end)



QBCore.Functions.CreateUseableItem('md_ginger_ale', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('md_ginger_ale', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('dom_perignon', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('dom_perignon', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('hennessy_shot', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('hennessy_shot', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('patron_margarita', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('patron_margarita', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('pearls_coffee', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('pearls_coffee', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('ps_dr_pepper', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('ps_dr_pepper', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('ps_sprite', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('ps_sprite', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

QBCore.Functions.CreateUseableItem('ps_coca_cola', function(source)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.RemoveItem('ps_coca_cola', 1)
    TriggerClientEvent('ak47_pearls:add', source, 'thirst', 50)
    TriggerClientEvent('ak47_pearls:onDrink', source)
end)

RegisterNetEvent('ak47_pearls:SetMetaData', function(type, amount)
    local xPlayer = QBCore.Functions.GetPlayer(source)
    xPlayer.Functions.SetMetaData(type, amount)
    if type == 'hunger' then
        TriggerClientEvent('hud:client:UpdateNeeds', source, amount, xPlayer.PlayerData.metadata.thirst)
    else
        TriggerClientEvent('hud:client:UpdateNeeds', source, xPlayer.PlayerData.metadata.hunger, amount)
    end
end)

