--Disease Triggered
RegisterNetEvent('SleepOrSex:hiv')
AddEventHandler('SleepOrSex:hiv', function()
	CreateThread(function()
		local playerPed = PlayerPedId()
		loadAnimSet('anim_group_move_ballistic')
      	SetPedMovementClipset(playerPed, 'anim_group_move_ballistic', true)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	SetTimecycleModifier('StuntSlowDark')
      	SetPedMotionBlur(playerPed, true)
      	SetPedIsDrunk(playerPed, true)
	end)
end)

RegisterNetEvent('SleepOrSex:hepatitis')
AddEventHandler('SleepOrSex:hepatitis', function()
	CreateThread(function()
		local playerPed = PlayerPedId()
		loadAnimSet('anim_group_move_ballistic')
      	SetPedMovementClipset(playerPed, 'anim_group_move_ballistic', true)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	SetTimecycleModifier('StuntSlowDark')
      	SetPedMotionBlur(playerPed, true)
      	SetPedIsDrunk(playerPed, true)
	end)
end)

RegisterNetEvent('SleepOrSex:gonore')
AddEventHandler('SleepOrSex:gonore', function()
	CreateThread(function()
		local playerPed = PlayerPedId()
		loadAnimSet('anim_group_move_ballistic')
      	SetPedMovementClipset(playerPed, 'anim_group_move_ballistic', true)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	SetTimecycleModifier('StuntSlowDark')
      	SetPedMotionBlur(playerPed, true)
      	SetPedIsDrunk(playerPed, true)
	end)
end)

RegisterNetEvent('SleepOrSex:klamidia')
AddEventHandler('SleepOrSex:klamidia', function()
	CreateThread(function()
		local playerPed = PlayerPedId()
		loadAnimSet('anim_group_move_ballistic')
      	SetPedMovementClipset(playerPed, 'anim_group_move_ballistic', true)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	Wait(500)
	  	ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 3.0)
	  	DoScreenFadeIn(500)
	  	Wait(500)
	  	SetTimecycleModifier('StuntSlowDark')
      	SetPedMotionBlur(playerPed, true)
      	SetPedIsDrunk(playerPed, true)
	end)
end)

-- Disease Animation
CreateThread(function()
	while true do
		local secondsBetweenAnim = math.random(100000, 500000)
	  	local playerPed = PlayerPedId()
	  	local maxHealth = GetEntityMaxHealth(playerPed)
	  	local health = GetEntityHealth(playerPed)
	  	local newHealth = math.min(maxHealth , math.floor(health - maxHealth/20))

	  	Wait(secondsBetweenAnim)
		
		-- i'm pretty sure IsPedDeadOrDying() is not working correctly for someone who have animation for dying, figure it out and change that!
	  	if hiv and not IsPedDeadOrDying() and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and not IsPedInAnyVehicle(ped, true) then
			DebugMode('Playing HIV Animation')
			loadAnimDict('oddjobs@taxi@tie')
			TaskPlayAnim(playerPed, 'oddjobs@taxi@tie', 'vomit_outside', 8.0, 8.0, -1, 50, 0, false, false, false)
			Wait(7000)
			ClearPedTasks(playerPed)
			--Some Effect after animation
			SetEntityHealth(playerPed, newHealth)
		elseif hepatitis and not IsPedDeadOrDying() and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and not IsPedInAnyVehicle(ped, true) then
			DebugMode('Playing Hepatitis Animation')
			loadAnimDict('oddjobs@taxi@tie')
			TaskPlayAnim(playerPed, 'oddjobs@taxi@tie', 'vomit_outside', 8.0, 8.0, -1, 50, 0, false, false, false)
			Wait(7000)
			ClearPedTasks(playerPed)
			SetEntityHealth(playerPed, newHealth)

		-- add your custom gonore & klamidia here, if you want

		-- // gonore function
		-- elseif gonore and not IsPedDeadOrDying() and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and not IsPedInAnyVehicle(ped, true) then
		--	DebugMode('Playing Gonore Animation')
		--	loadAnimDict('oddjobs@taxi@tie')
		--	TaskPlayAnim(playerPed, 'oddjobs@taxi@tie', 'vomit_outside', 8.0, 8.0, -1, 50, 0, false, false, false)
		--	Wait(7000)
		--	ClearPedTasks(playerPed)
		--	SetEntityHealth(playerPed, newHealth)

		-- // klamidia function
		-- elseif klamidia and not IsPedDeadOrDying() and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and not IsPedInAnyVehicle(ped, true) then
		--	DebugMode('Playing Hlamidia Animation')
		--	loadAnimDict('oddjobs@taxi@tie')
		--	TaskPlayAnim(playerPed, 'oddjobs@taxi@tie', 'vomit_outside', 8.0, 8.0, -1, 50, 0, false, false, false)
		--	Wait(7000)
		--	ClearPedTasks(playerPed)
		--	SetEntityHealth(playerPed, newHealth)
	  	end
	end
end)

--Cured Disease
RegisterNetEvent('SleepOrSex:hiv_cured')
AddEventHandler('SleepOrSex:hiv_cured', function()
  	hiv = false
  	local playerPed  = PlayerPedId()
	loadAnimDict('mp_suicide')
  	TaskPlayAnim(playerPed, 'mp_suicide', 'pill_fp', 8.0, 8.0, -1, 50, 0, false, false, false)
  	Wait(3000)
  	ClearPedTasks(playerPed)
  	TriggerServerEvent('SleepOrSex:valuedisease', 'cured')
   	ClearTimecycleModifier()
    ResetScenarioTypesEnabled()
    ResetPedMovementClipset(playerPed, 0)
    SetPedIsDrunk(playerPed, false)
    SetPedMotionBlur(playerPed, false)
	-- Notification here
  	-- ShowNotification('Cured from hiv')
end)

RegisterNetEvent('SleepOrSex:hepatitis_cured')
AddEventHandler('SleepOrSex:hepatitis_cured', function()
	hepatitis = false
  	local playerPed  = PlayerPedId()
	loadAnimDict('mp_suicide')
  	TaskPlayAnim(playerPed, 'mp_suicide', 'pill_fp', 8.0, 8.0, -1, 50, 0, false, false, false)
  	Wait(3000)
  	ClearPedTasks(playerPed)
  	TriggerServerEvent('SleepOrSex:valuedisease', 'cured')
   	ClearTimecycleModifier()
    ResetScenarioTypesEnabled()
    ResetPedMovementClipset(playerPed, 0)
    SetPedIsDrunk(playerPed, false)
    SetPedMotionBlur(playerPed, false)
	-- Notification here
  	-- ShowNotification('Cured from hepatitis')
end)

RegisterNetEvent('SleepOrSex:gonore_cured')
AddEventHandler('SleepOrSex:gonore_cured', function()
	gonore = false
  	local playerPed  = PlayerPedId()
	loadAnimDict('mp_suicide')
  	TaskPlayAnim(playerPed, 'mp_suicide', 'pill_fp', 8.0, 8.0, -1, 50, 0, false, false, false)
  	Wait(3000)
  	ClearPedTasks(playerPed)
  	TriggerServerEvent('SleepOrSex:valuedisease', 'cured')
   	ClearTimecycleModifier()
    ResetScenarioTypesEnabled()
    ResetPedMovementClipset(playerPed, 0)
    SetPedIsDrunk(playerPed, false)
    SetPedMotionBlur(playerPed, false)
	-- Notification here
  	-- ShowNotification('Cured from gonore')
end)

RegisterNetEvent('SleepOrSex:klamidia_cured')
AddEventHandler('SleepOrSex:klamidia_cured', function()
	klamidia = false
  	local playerPed  = PlayerPedId()
	loadAnimDict('mp_suicide')
  	TaskPlayAnim(playerPed, 'mp_suicide', 'pill_fp', 8.0, 8.0, -1, 50, 0, false, false, false)
  	Wait(3000)
  	ClearPedTasks(playerPed)
  	TriggerServerEvent('SleepOrSex:valuedisease', 'cured')
   	ClearTimecycleModifier()
    ResetScenarioTypesEnabled()
    ResetPedMovementClipset(playerPed, 0)
    SetPedIsDrunk(playerPed, false)
    SetPedMotionBlur(playerPed, false)
	-- Notification here
  	-- ShowNotification('Cured from klamidia')
end)