Props = Props or {}

Props = {
    ["Baby Pack"] = {
        { label = "Ped",        model = "ad_brinquedo_13b",                  desc = ""},
        { label = "Baby",        model = "bag_baby",                  desc = ""},
        { label = "Swing",        model = "balanco_sakura",                  desc = ""},
        { label = "Teddy",        model = "bbywtch_plush1",                  desc = ""},
        { label = "Teddy 2",        model = "bbywtch_plush2",                  desc = ""},
        { label = "Teddy 3",        model = "denis3d_teddyboe",                  desc = ""},
        { label = "Teddy 4",        model = "denis3d_teddydovahpug",                  desc = ""},
        { label = "Teddy 5",        model = "denis3d_teddygrub",                  desc = ""},
        { label = "Teddy 6",        model = "denis3d_teddystarkey",                  desc = ""},
        { label = "Teddy 7",        model = "dr_pets_1",                  desc = ""},
        { label = "Teddy 8",        model = "dr_pets_2",                  desc = ""},
        { label = "Teddy 9",        model = "dr_pets_3",                  desc = ""},
        { label = "Teddy 10",        model = "dr_pets_4",                  desc = ""},
        { label = "Teddy 11",        model = "dr_pets_5",                  desc = ""},
        { label = "Teddy 12",        model = "dr_pets_6",                  desc = ""},
        { label = "Teddy 13",        model = "dr_pets_7",                  desc = ""},
        { label = "Teddy 14",        model = "dr_pets_8",                  desc = ""},
        { label = "Teddy 15",        model = "uni_boneco_02",                  desc = ""},
        { label = "Teddy 16",        model = "uni_boneco_03",                  desc = ""},
        { label = "Teddy 17",        model = "urso_coracaoazul_sakura",                  desc = ""},
        { label = "Teddy 18",        model = "urso_coracaorosa_sakura",                  desc = ""},
        { label = "Teddy 19",        model = "urso_deitadinho_sakura",                  desc = ""},
        { label = "Teddy 20",        model = "urso_rosa_sakura",                  desc = ""},
        { label = "Teddy 21",        model = "vertexgroup_bear_01",                  desc = ""},
        { label = "Teddy 22",        model = "vertexgroup_bear_02",                  desc = ""},
        { label = "Teddy 23",        model = "vertexgroup_box_bear",                  desc = ""},
        { label = "Shitter",        model = "caixaareia_sakura",                  desc = ""},
        { label = "Toy box",        model = "caixabrinquedo_sakura",                  desc = ""},
        { label = "Flower",        model = "flor_sakura",                  desc = ""},
        { label = "Flower 2",        model = "sakura_item_16",                  desc = ""},
        { label = "Flower 3",        model = "sakura_item_17",                  desc = ""},
        { label = "Plants",        model = "plantinhas_sakura",                  desc = ""},
        { label = "Chocolate",        model = "sakura_item_21",                  desc = ""},
        { label = "Chocolate 2",        model = "sakura_item_22",                  desc = ""},
        { label = "Chocolate 3",        model = "vertexgroup_box_open_01",                  desc = ""},
        { label = "Sofa Kawai",        model = "sofa_ursoazul_sakura",                  desc = ""},
        { label = "Sofa Kawai 2",        model = "sofa_ursorosa_sakura",                  desc = ""},
        { label = "Camping",        model = "tenda_kid_sakura",                  desc = ""},
        { label = "Camping 2",        model = "vertexgroup_towel",                  desc = ""},
        { label = "Theme Park",        model = "uni_escorregador_01a",                  desc = ""},
        { label = "Picnic",        model = "uni_piquinique_01a",                  desc = ""},
        { label = "Pokémon",        model = "uni_pokemon_01",                  desc = ""},
        { label = "Pokémon 2",        model = "uni_pokemon_02b",                  desc = ""},
        { label = "Kid Carpet",        model = "uni_tapete_escola_01a",                  desc = ""},
        { label = "Bike",        model = "vertexgroup_bike_flower",                  desc = ""},
        { label = "Ceste",        model = "vertexgroup_box_ceste_01",                  desc = ""},
        { label = "Ceste 2",        model = "vertexgroup_cesta",                  desc = ""},
        { label = "Decoration",        model = "vertexgroup_box_decoration_01",                  desc = ""},
        { label = "Decoration 2",        model = "vertexgroup_box_decoration_02",                  desc = ""},
        { label = "Heart",        model = "vertexgroup_heart_01",                  desc = ""},
        { label = "Love",        model = "vertexgroup_love_sing",                  desc = ""},
        { label = "Love 2",        model = "vertexgroup_quad_love",                  desc = ""},
        { label = "Pillows",        model = "vertexgroup_pillows",                  desc = ""},
    },
    ["Electronic Pack"] = {
        { label = "Decoration Electronic 1",        model = "dnxprops_buildings_canopysmall01_a",                  desc = ""},
        { label = "Decoration Electronic 2",        model = "dnxprops_buildings_canopysmall02_a",                  desc = ""},
        { label = "Decoration Electronic 3",        model = "dnxprops_buildings_canopysmall03_a",                  desc = ""},
        { label = "Decoration Electronic 4",        model = "dnxprops_buildings_canopysmall04_a",                  desc = ""},
        { label = "Decoration Electronic 5",        model = "dnxprops_buildings_canopysmall05_a",                  desc = ""},
        { label = "Decoration Electronic 6",        model = "dnxprops_buildings_canopysmall06_a",                  desc = ""},
        { label = "Privacy Screen 1",        model = "dnxprops_buildings_privacyscreen01_a",                  desc = ""},
        { label = "Privacy Screen 2",        model = "dnxprops_buildings_privacyscreen01_a_hedge",                  desc = ""},
        { label = "Fire",        model = "dnxprops_effects_fire_campfire",                  desc = ""},
        { label = "Fire 2",        model = "dnxprops_effects_fire_fireplace",                  desc = ""},
        { label = "Book 1",        model = "dnxprops_entertainment_manga01_a",                  desc = ""},
        { label = "Book 2",        model = "dnxprops_entertainment_manga01_b",                  desc = ""},
        { label = "Book 3",        model = "dnxprops_entertainment_manga01_c",                  desc = ""},
        { label = "Book 4",        model = "dnxprops_entertainment_manga01_d",                  desc = ""},
        { label = "Book 5",        model = "dnxprops_entertainment_manga01_e",                  desc = ""},
        { label = "Bathroom Cabinet",        model = "dnxprops_furniture_bathroomcabinet01_a",                  desc = ""},
        { label = "Bathroom Cabinet 2",        model = "dnxprops_furniture_bathroomcabinet01_b",                  desc = ""},
        { label = "Bathroom Cabinet 3",        model = "dnxprops_furniture_bathroomcabinet01_c",                  desc = ""},
        { label = "Bathroom Sink",        model = "dnxprops_furniture_bathroomsink01_a",                  desc = ""},
        { label = "Bathroom Tub",        model = "dnxprops_furniture_bathtub02_a",                  desc = ""},
        { label = "Bathroom Bidet",        model = "dnxprops_furniture_bidet",                  desc = ""},
        { label = "Coatrack",        model = "dnxprops_furniture_coatrack01_a",                  desc = ""},
        { label = "Coatrack 2",        model = "dnxprops_furniture_coatrack01_b",                  desc = ""},
        { label = "Coatrack 3",        model = "dnxprops_furniture_coatrack01_c",                  desc = ""},
        { label = "Desk 1",        model = "dnxprops_furniture_desk01_a",                  desc = ""},
        { label = "Desk 2",        model = "dnxprops_furniture_desk01_b",                  desc = ""},
        { label = "Desk 3",        model = "dnxprops_furniture_desk01_c",                  desc = ""},
        { label = "Desk 4",        model = "dnxprops_furniture_desk02_a",                  desc = ""},
        { label = "Desk 5",        model = "dnxprops_furniture_desk02_b",                  desc = ""},
        { label = "Desk 6",        model = "dnxprops_furniture_desk02_c",                  desc = ""},
        { label = "Desk 7",        model = "dnxprops_furniture_desk03_a",                  desc = ""},
        { label = "Desk 8",        model = "dnxprops_furniture_desk03_b",                  desc = ""},
        { label = "Desk 9",        model = "dnxprops_furniture_desk03_c",                  desc = ""},
        { label = "Desk 10",        model = "dnxprops_furniture_desk04_a",                  desc = ""},
        { label = "Desk 11",        model = "dnxprops_furniture_desk04_b",                  desc = ""},
        { label = "Desk 12",        model = "dnxprops_furniture_desk04_c",                  desc = ""},
        { label = "Desk 13",        model = "dnxprops_furniture_desk05_a",                  desc = ""},
        { label = "Desk 14",        model = "dnxprops_furniture_desk05_b",                  desc = ""},
        { label = "Desk 15",        model = "dnxprops_furniture_desk05_c",                  desc = ""},
        { label = "Desk 16",        model = "dnxprops_furniture_desk06_a",                  desc = ""},
        { label = "Desk 17",        model = "dnxprops_furniture_desk06_b",                  desc = ""},
        { label = "Desk 18",        model = "dnxprops_furniture_desk06_c",                  desc = ""},
        { label = "Desk 19",        model = "dnxprops_furniture_desk07_a",                  desc = ""},
        { label = "Desk 20",        model = "dnxprops_furniture_desk07_b",                  desc = ""},
        { label = "Desk 21",        model = "dnxprops_furniture_desk07_c",                  desc = ""},
        { label = "Desk 22",        model = "dnxprops_furniture_desk08_a",                  desc = ""},
        { label = "Desk 23",        model = "dnxprops_furniture_desk08_b",                  desc = ""},
        { label = "Desk 24",        model = "dnxprops_furniture_desk08_c",                  desc = ""},
        { label = "Desk 25",        model = "dnxprops_furniture_desk09_a",                  desc = ""},
        { label = "Desk 26",        model = "dnxprops_furniture_desk09_b",                  desc = ""},
        { label = "Desk 27",        model = "dnxprops_furniture_desk09_c",                  desc = ""},
        { label = "Desk 28",        model = "dnxprops_furniture_desk10_a",                  desc = ""},
        { label = "Desk 29",        model = "dnxprops_furniture_desk10_b",                  desc = ""},
        { label = "Desk 30",        model = "dnxprops_furniture_desk10_c",                  desc = ""},
        { label = "Desk 31",        model = "dnxprops_furniture_desk11_a",                  desc = ""},
        { label = "Desk 32",        model = "dnxprops_furniture_desk11_b",                  desc = ""},
        { label = "Desk 33",        model = "dnxprops_furniture_desk11_c",                  desc = ""},
        { label = "Desk 34",        model = "dnxprops_furniture_desk12_a",                  desc = ""},
        { label = "Desk 35",        model = "dnxprops_furniture_desk12_b",                  desc = ""},
        { label = "Desk 36",        model = "dnxprops_furniture_desk12_c",                  desc = ""},
        { label = "Desk 37",        model = "dnxprops_furniture_desk13_a",                  desc = ""},
        { label = "Desk 38",        model = "dnxprops_furniture_desk13_b",                  desc = ""},
        { label = "Desk 39",        model = "dnxprops_furniture_desk13_c",                  desc = ""},
        { label = "Desk 40",        model = "dnxprops_furniture_deskwood01_a",                  desc = ""},
        { label = "Desk 41",        model = "dnxprops_furniture_deskwood01_b",                  desc = ""},
        { label = "Desk 42",        model = "dnxprops_furniture_deskwood01_c",                  desc = ""},
        { label = "Dinning Table 1",        model = "dnxprops_furniture_dinningtable01_a",                  desc = ""},
        { label = "Dinning Table 2",        model = "dnxprops_furniture_dinningtable01_b",                  desc = ""},
        { label = "Dinning Table 3",        model = "dnxprops_furniture_dinningtable02_a",                  desc = ""},
        { label = "Dinning Table 4",        model = "dnxprops_furniture_dinningtable02_b",                  desc = ""},
        { label = "Cabinet Large 1",        model = "dnxprops_furniture_filecabinetlarge01_a",                  desc = ""},
        { label = "Cabinet Large 2",        model = "dnxprops_furniture_filecabinetlarge01_b",                  desc = ""},
        { label = "Cabinet Large 3",        model = "dnxprops_furniture_filecabinetlarge02_a",                  desc = ""},
        { label = "Cabinet Large 4",        model = "dnxprops_furniture_filecabinetlarge02_b",                  desc = ""},
        { label = "Chocolate 2",        model = "sakura_item_22",                  desc = ""},
        { label = "Chocolate 3",        model = "vertexgroup_box_open_01",                  desc = ""},
        { label = "Sofa Kawai",        model = "sofa_ursoazul_sakura",                  desc = ""},
        { label = "Sofa Kawai 2",        model = "sofa_ursorosa_sakura",                  desc = ""},
        { label = "Camping",        model = "tenda_kid_sakura",                  desc = ""},
        { label = "Camping 2",        model = "vertexgroup_towel",                  desc = ""},
        { label = "Theme Park",        model = "uni_escorregador_01a",                  desc = ""},
        { label = "Picnic",        model = "uni_piquinique_01a",                  desc = ""},
        { label = "Pokémon",        model = "uni_pokemon_01",                  desc = ""},
        { label = "Pokémon 2",        model = "uni_pokemon_02b",                  desc = ""},
        { label = "Kid Carpet",        model = "uni_tapete_escola_01a",                  desc = ""},
        { label = "Bike",        model = "vertexgroup_bike_flower",                  desc = ""},
        { label = "Ceste",        model = "vertexgroup_box_ceste_01",                  desc = ""},
        { label = "Ceste 2",        model = "vertexgroup_cesta",                  desc = ""},
        { label = "Decoration",        model = "vertexgroup_box_decoration_01",                  desc = ""},
        { label = "Decoration 2",        model = "vertexgroup_box_decoration_02",                  desc = ""},
        { label = "Heart",        model = "vertexgroup_heart_01",                  desc = ""},
        { label = "Love",        model = "vertexgroup_love_sing",                  desc = ""},
        { label = "Love 2",        model = "vertexgroup_quad_love",                  desc = ""},
        { label = "Pillows",        model = "vertexgroup_pillows",                  desc = ""},
        { label = "Kitchen Cabinet",        model = "dnxprops_furniture_kitchencabinet01_a",                  desc = ""},
        { label = "Kitchen Cabinet 2",        model = "dnxprops_furniture_kitchencabinet01_b",                  desc = ""},
        { label = "Kitchen Cabinet 3",        model = "dnxprops_furniture_kitchencabinet02_a",                  desc = ""},
        { label = "Kitchen Cabinet 4",        model = "dnxprops_furniture_kitchencabinet02_b",                  desc = ""},
        { label = "Kitchen Cabinet 5",        model = "dnxprops_furniture_kitchencabinet03_a",                  desc = ""},
        { label = "Kitchen Cabinet 6",        model = "dnxprops_furniture_kitchencabinet03_b",                  desc = ""},
        { label = "Kitchen Cabinet 7",        model = "dnxprops_furniture_kitchencabinet04_a",                  desc = ""},
        { label = "Kitchen Cabinet 8",        model = "dnxprops_furniture_kitchencabinet04_b",                  desc = ""},
        { label = "Kitchen Cabinet 9",        model = "dnxprops_furniture_kitchencabinet05_a",                  desc = ""},
        { label = "Kitchen Cabinet 10",        model = "dnxprops_furniture_kitchencabinet05_b",                  desc = ""},
        { label = "Kitchen Cabinet 11",        model = "dnxprops_furniture_kitchencabinet06_a",                  desc = ""},
        { label = "Kitchen Cabinet 12",        model = "dnxprops_furniture_kitchencabinet06_b",                  desc = ""},
        { label = "Kitchen Cabinet 13",        model = "dnxprops_furniture_kitchencabinet07_a",                  desc = ""},
        { label = "Kitchen Cabinet 14",        model = "dnxprops_furniture_kitchencabinet07_b",                  desc = ""},
        { label = "Kitchen Cabinet 15",        model = "dnxprops_furniture_kitchencabinet08_a",                  desc = ""},
        { label = "Kitchen Cabinet 16",        model = "dnxprops_furniture_kitchencabinet08_b",                  desc = ""},
        { label = "Kitchen Cabinet 17",        model = "dnxprops_furniture_kitchencabinet09_a",                  desc = ""},
        { label = "Kitchen Cabinet 18",        model = "dnxprops_furniture_kitchencabinet09_b",                  desc = ""},
        { label = "Kitchen Cabinet 19",        model = "dnxprops_furniture_kitchencabinet10_a",                  desc = ""},
        { label = "Shower",        model = "dnxprops_furniture_shower01_a",                  desc = ""},
        { label = "Shower 2",        model = "dnxprops_furniture_shower03_a",                  desc = ""},
        { label = "Toilet",        model = "dnxprops_furniture_toilet01_a",                  desc = ""},
        { label = "Toilet 2",        model = "dnxprops_furniture_toilet01_b",                  desc = ""},
        { label = "Toilet 3",        model = "dnxprops_furniture_toilet01_c",                  desc = ""},
        { label = "Organizer",        model = "dnxprops_home_bathroomorganizer01_a_empty",                  desc = ""},
        { label = "Ceramic Bowl",        model = "dnxprops_home_ceramicbowl01_a",                  desc = ""},
        { label = "Ceramic Bowl 2",        model = "dnxprops_home_ceramicbowl01_b",                  desc = ""},
        { label = "Ceramic Bowl 3",        model = "dnxprops_home_ceramicbowl01_c",                  desc = ""},
        { label = "Desk Organizer",        model = "dnxprops_home_deskorganizer01_a",                  desc = ""},
        { label = "Desk Organizer 2",        model = "dnxprops_home_deskorganizer01_a",                  desc = ""},
        { label = "Desk Organizer 3",        model = "dnxprops_home_deskorganizer01_b",                  desc = ""},
        { label = "Desk Organizer 4",        model = "dnxprops_home_deskorganizer01_c",                  desc = ""},
        { label = "Desk Organizer 5",        model = "dnxprops_home_deskorganizer02_a",                  desc = ""},
        { label = "Desk Organizer 6",        model = "dnxprops_home_deskorganizer02_b",                  desc = ""},
        { label = "Digital Bath Roomscale",        model = "dnxprops_home_digitalbathroomscale01_a",                  desc = ""},
        { label = "Digital Bath Roomscale 2",        model = "dnxprops_home_digitalbathroomscale01_b",                  desc = ""},
        { label = "Lantern",        model = "dnxprops_home_lantern01_a_empty",                  desc = ""},
        { label = "Lantern 2",        model = "dnxprops_home_lantern02_a_empty",                  desc = ""},
        { label = "Liquid Soap",        model = "dnxprops_home_liquidsoap01_a",                  desc = ""},
        { label = "Mirror",        model = "dnxprops_home_mirror01_a",                  desc = ""},
        { label = "Mirror 2",        model = "dnxprops_home_mirror01_b",                  desc = ""},
        { label = "Mirror 3",        model = "dnxprops_home_mirror01_c",                  desc = ""},
        { label = "Mirror 4",        model = "dnxprops_home_mirror02_a",                  desc = ""},
        { label = "Mirror 5",        model = "dnxprops_home_mirror02_b",                  desc = ""},
        { label = "Mirror 6",        model = "dnxprops_home_mirror02_c",                  desc = ""},
        { label = "Mirror 7",        model = "dnxprops_home_mirror03_a",                  desc = ""},
        { label = "Mirror 8",        model = "dnxprops_home_mirror03_b",                  desc = ""},
        { label = "Mirror 9",        model = "dnxprops_home_mirror03_c",                  desc = ""},
        { label = "Mirror 10",        model = "dnxprops_home_mirror04_a",                  desc = ""},
        { label = "Mirror 11",        model = "dnxprops_home_mirror04_b",                  desc = ""},
        { label = "Mirror 2",        model = "dnxprops_home_mirror04_c",                  desc = ""},
        { label = "Strawcup",        model = "dnxprops_home_strawcup",                  desc = ""},
        { label = "Toilet Brush",        model = "dnxprops_home_toiletbrush01_a",                  desc = ""},
        { label = "Toilet Brush 2",        model = "dnxprops_home_toiletbrush02_a",                  desc = ""},
        { label = "Towel Rail",        model = "dnxprops_home_towelrail01_a",                  desc = ""},
        { label = "Towel Rail 2",        model = "dnxprops_home_towelrail01_b",                  desc = ""},
        { label = "Towel Rail 3",        model = "dnxprops_home_towelrail01_c",                  desc = ""},
        { label = "Picket Light",        model = "dnxprops_lighting_picketlight01_a",                  desc = ""},
        { label = "Picket Light 2",        model = "dnxprops_lighting_picketlight02_a",                  desc = ""},
        { label = "Guitar Wall Mount",        model = "dnxprops_music_guitarwallmount01_a",                  desc = ""},
        { label = "Keyboard",        model = "dnxprops_music_keyboard01_a_88",                  desc = ""},
        { label = "Keyboard Stand",        model = "dnxprops_music_keyboardstand01_a",                  desc = ""},
        { label = "Gaming Chair",        model = "dnxprops_tech_gamingchair01_black",                  desc = ""},
        { label = "Gaming Chair 2",        model = "dnxprops_tech_gamingchair01_blue",                  desc = ""},
        { label = "Gaming Chair 3",        model = "dnxprops_tech_gamingchair01_green",                  desc = ""},
        { label = "Gaming Chair 4",        model = "dnxprops_tech_gamingchair01_pink",                  desc = ""},
        { label = "Gaming Chair 5",        model = "dnxprops_tech_gamingchair01_purple",                  desc = ""},
        { label = "Gaming Chair 6",        model = "dnxprops_tech_gamingchair01_red",                  desc = ""},
        { label = "Gaming Chair 7 ",        model = "dnxprops_tech_gamingchair01_white",                  desc = ""},
        { label = "Gaming Chair 8",        model = "dnxprops_tech_gamingchair01_yellow",                  desc = ""},
        { label = "Gaming Keyboard",        model = "dnxprops_tech_gamingkeyboard01_a_blue",                  desc = ""},
        { label = "Gaming Keyboard 2",        model = "dnxprops_tech_gamingkeyboard01_a_cyan",                  desc = ""},
        { label = "Gaming Keyboard 3",        model = "dnxprops_tech_gamingkeyboard01_a_green",                  desc = ""},
        { label = "Gaming Keyboard 4",        model = "dnxprops_tech_gamingkeyboard01_a_off",                  desc = ""},
        { label = "Gaming Keyboard 5",        model = "dnxprops_tech_gamingkeyboard01_a_purple",                  desc = ""},
        { label = "Gaming Keyboard 6",        model = "dnxprops_tech_gamingkeyboard01_a_red",                  desc = ""},
        { label = "Gaming Keyboard 7",        model = "dnxprops_tech_gamingkeyboard01_a_rgb1",                  desc = ""},
        { label = "Gaming Keyboard 8",        model = "dnxprops_tech_gamingkeyboard01_a_rgb2",                  desc = ""},
        { label = "Gaming Keyboard 9",        model = "dnxprops_tech_gamingkeyboard01_a_yellow",                  desc = ""},
        { label = "Gaming Keyboard 10",        model = "dnxprops_tech_gamingkeyboard01_b_blue",                  desc = ""},
        { label = "Gaming Keyboard 11",        model = "dnxprops_tech_gamingkeyboard01_b_cyan",                  desc = ""},
        { label = "Gaming Keyboard 12",        model = "dnxprops_tech_gamingkeyboard01_b_green",                  desc = ""},
        { label = "Gaming Keyboard 13",        model = "dnxprops_tech_gamingkeyboard01_b_off",                  desc = ""},
        { label = "Gaming Keyboard 14",        model = "dnxprops_tech_gamingkeyboard01_b_purple",                  desc = ""},
        { label = "Gaming Keyboard 15",        model = "dnxprops_tech_gamingkeyboard01_b_red",                  desc = ""},
        { label = "Gaming Keyboard 16",        model = "dnxprops_tech_gamingkeyboard01_b_rgb1",                  desc = ""},
        { label = "Gaming Keyboard 17",        model = "dnxprops_tech_gamingkeyboard01_b_rgb2",                  desc = ""},
        { label = "Gaming Keyboard 18",        model = "dnxprops_tech_gamingkeyboard01_b_yellow",                  desc = ""},
        { label = "Gaming Monitor",        model = "dnxprops_tech_gamingmonitor01_a_27_off",                  desc = ""},
        { label = "Gaming Monitor 2",        model = "dnxprops_tech_gamingmonitor01_a_27_wp1",                  desc = ""},
        { label = "Gaming Monitor 3",        model = "dnxprops_tech_gamingmonitor01_a_27_wp2",                  desc = ""},
        { label = "Gaming Mouse",        model = "dnxprops_tech_gamingmouse01_a_blue",                  desc = ""},
        { label = "Gaming Mouse 2",        model = "dnxprops_tech_gamingmouse01_a_cyan",                  desc = ""},
        { label = "Gaming Mouse 3",        model = "dnxprops_tech_gamingmouse01_a_green",                  desc = ""},
        { label = "Gaming Mouse 4",        model = "dnxprops_tech_gamingmouse01_a_off",                  desc = ""},
        { label = "Gaming Mouse 5",        model = "dnxprops_tech_gamingmouse01_a_purple",                  desc = ""},
        { label = "Gaming Mouse 6",        model = "dnxprops_tech_gamingmouse01_a_red",                  desc = ""},
        { label = "Gaming Mouse 7",        model = "dnxprops_tech_gamingmouse01_a_rgb1",                  desc = ""},
        { label = "Gaming Mouse 8",        model = "dnxprops_tech_gamingmouse01_a_rgb2",                  desc = ""},
        { label = "Gaming Mouse 9",        model = "dnxprops_tech_gamingmouse01_a_yellow",                  desc = ""},
        { label = "Gaming Mouse 10",        model = "dnxprops_tech_gamingmouse01_b_blue",                  desc = ""},
        { label = "Gaming Mouse 11",        model = "dnxprops_tech_gamingmouse01_b_cyan",                  desc = ""},
        { label = "Gaming Mouse 12",        model = "dnxprops_tech_gamingmouse01_b_green",                  desc = ""},
        { label = "Gaming Mouse 13",        model = "dnxprops_tech_gamingmouse01_b_off",                  desc = ""},
        { label = "Gaming Mouse 14",        model = "dnxprops_tech_gamingmouse01_b_purple",                  desc = ""},
        { label = "Gaming Mouse 15",        model = "dnxprops_tech_gamingmouse01_b_red",                  desc = ""},
        { label = "Gaming Mouse 16",        model = "dnxprops_tech_gamingmouse01_b_rgb1",                  desc = ""},
        { label = "Gaming Mouse 17",        model = "dnxprops_tech_gamingmouse01_b_rgb2",                  desc = ""},
        { label = "Gaming Mouse 18",        model = "dnxprops_tech_gamingmouse01_b_yellow",                  desc = ""},
        { label = "Gaming Mouse Pad",        model = "dnxprops_tech_gamingmousepad01_a_blue",                  desc = ""},
        { label = "Gaming Mouse Pad 2",        model = "dnxprops_tech_gamingmousepad01_a_cyan",                  desc = ""},
        { label = "Gaming Mouse Pad 3",        model = "dnxprops_tech_gamingmousepad01_a_green",                  desc = ""},
        { label = "Gaming Mouse Pad 4",        model = "dnxprops_tech_gamingmousepad01_a_off",                  desc = ""},
        { label = "Gaming Mouse Pad 5",        model = "dnxprops_tech_gamingmousepad01_a_purple",                  desc = ""},
        { label = "Gaming Mouse Pad 6",        model = "dnxprops_tech_gamingmousepad01_a_red",                  desc = ""},
        { label = "Gaming Mouse Pad 7",        model = "dnxprops_tech_gamingmousepad01_a_rgb1",                  desc = ""},
        { label = "Gaming Mouse Pad 8",        model = "dnxprops_tech_gamingmousepad01_a_rgb2",                  desc = ""},
        { label = "Gaming Mouse Pad 9",        model = "dnxprops_tech_gamingmousepad01_a_yellow",                  desc = ""},
        { label = "Gaming PC",        model = "dnxprops_tech_gamingpc01_a_blue",                  desc = ""},
        { label = "Gaming PC 2",        model = "dnxprops_tech_gamingpc01_a_cyan",                  desc = ""},
        { label = "Gaming PC 3",        model = "dnxprops_tech_gamingpc01_a_green",                  desc = ""},
        { label = "Gaming PC 4",        model = "dnxprops_tech_gamingpc01_a_off",                  desc = ""},
        { label = "Gaming PC 5",        model = "dnxprops_tech_gamingpc01_a_purple",                  desc = ""},
        { label = "Gaming PC 6",        model = "dnxprops_tech_gamingpc01_a_red",                  desc = ""},
        { label = "Gaming PC 7",        model = "dnxprops_tech_gamingpc01_a_rgb1",                  desc = ""},
        { label = "Gaming PC 8",        model = "dnxprops_tech_gamingpc01_a_rgb2",                  desc = ""},
        { label = "Gaming PC 9",        model = "dnxprops_tech_gamingpc01_a_yellow",                  desc = ""},
        { label = "Gaming PC Case",        model = "dnxprops_tech_gamingpccase01_a",                  desc = ""},
        { label = "Gaming PC Case 2",        model = "dnxprops_tech_gamingpccase01_b",                  desc = ""},
        { label = "Gaming PC Fan",        model = "dnxprops_tech_gamingpcfan01_b",                  desc = ""},
        { label = "Gaming PC GPU",        model = "dnxprops_tech_gamingpcgpu01_a",                  desc = ""},
        { label = "Gaming PC Motherboard",        model = "dnxprops_tech_gamingpcmotherboard01_a",                  desc = ""},
    },
    ["Haway Pack"] = {
        { label = "Capanna",        model = "capanna",                  desc = ""},
        { label = "Lanternanikki",        model = "lanternanikki",                  desc = ""},
        { label = "Lettino",        model = "lettino1",                  desc = ""},
        { label = "Lettino 2",        model = "lettino3",                  desc = ""},
        { label = "Chilling bed",        model = "sgb_barcellona",                  desc = ""},
        { label = "Beach Torch",        model = "sgb_beach_torch",                  desc = ""},
    },
    ["Furniture Pack"] = {
        { label = "Canto Show",        model = "aereo_canto_show",                  desc = ""},
        { label = "Maior",        model = "aereo_maior",                  desc = ""},
        { label = "Maior Bordoux",        model = "aereo_maior_bordoux",                  desc = ""},
        { label = "Maior Cinza",        model = "aereo_maior_cinza",                  desc = ""},
        { label = "Maior Show",        model = "aereo_maior_show",                  desc = ""},
        { label = "Menor",        model = "aereo_menor",                  desc = ""},
        { label = "Menor Bordoux",        model = "aereo_menor_bordoux",                  desc = ""},
        { label = "Cinza",        model = "aereo_menor_cinza",                  desc = ""},
        { label = "Show",        model = "aereo_menor_show",                  desc = ""},
        { label = "Flower Chair",        model = "atr_flower_chair",                  desc = ""},
        { label = "Vie Chair",        model = "atr_vie_chaiir",                  desc = ""},
        { label = "Vie Table",        model = "atr_vie_table",                  desc = ""},
        { label = "Balcao Canto",        model = "balcao_canto_show",                  desc = ""},
        { label = "Balcao Maior",        model = "balcao_maior_show",                  desc = ""},
        { label = "Balcao Menor",        model = "balcao_menor",                  desc = ""},
        { label = "Balcao Menor 2",        model = "balcao_menor_bordoux",                  desc = ""},
        { label = "Balcao Menor 3",        model = "balcao_menor_cinza",                  desc = ""},
        { label = "Balcao Pia Show",        model = "balcao_pia_show",                  desc = ""},
        { label = "Sofa",        model = "bazq_sofa2",                  desc = ""},
        { label = "Sofa 2",        model = "beauty_sofa",                  desc = ""},
        { label = "Boarhead",        model = "boarhead_beaten",                  desc = ""},
        { label = "Boarhead 2",        model = "boarhead_black",                  desc = ""},
        { label = "Boarhead 3",        model = "boarhead_brown",                  desc = ""},
        { label = "Boarhead 4",        model = "boarhead_red",                  desc = ""},
        { label = "Boarhead 5",        model = "boarhead_white",                  desc = ""},
        { label = "Chicken Hawk",        model = "chickenhawk",                  desc = ""},
        { label = "Corner Desk",        model = "corner_desk",                  desc = ""},
        { label = "Corner Desk 2",        model = "corner_desk2",                  desc = ""},
        { label = "Corner Desk 3",        model = "corner_desk3",                  desc = ""},
        { label = "Corner Desk 4",        model = "corner_desk4",                  desc = ""},
        { label = "Corner Desk 5",        model = "corner_desk5",                  desc = ""},
        { label = "Corner Desk 6",        model = "corner_desk6",                  desc = ""},
        { label = "Corner Desk 7",        model = "corner_desk7",                  desc = ""},
        { label = "Corner Desk 8",        model = "corner_desk8",                  desc = ""},
        { label = "Corner Desk 9",        model = "corner_desk9",                  desc = ""},
        { label = "Corner Desk 10",        model = "corner_desk10",                  desc = ""},
        { label = "Corner Desk 11",        model = "corner_desk11",                  desc = ""},
        { label = "Corner Desk 12",        model = "corner_desk12",                  desc = ""},
        { label = "Crescent Couch",        model = "crescent_couch",                  desc = ""},
        { label = "Deer Head",        model = "deerhead_brown",                  desc = ""},
        { label = "Deer Head 2",        model = "deerhead_brown2",                  desc = ""},
        { label = "Deer Tan",        model = "deerhead_tan",                  desc = ""},
        { label = "Deer White",        model = "deerhead_white",                  desc = ""},
        { label = "Dog House",        model = "denis3d_arthasdoghouse",                  desc = ""},
        { label = "Diamond Lamp",        model = "diamond_lamp",                  desc = ""},
        { label = "Desk",        model = "desk",                  desc = ""},
        { label = "Desk 2",        model = "desk2",                  desc = ""},
        { label = "Desk 3",        model = "desk3",                  desc = ""},
        { label = "Desk 4",        model = "desk4",                  desc = ""},
        { label = "Desk 5",        model = "desk5",                  desc = ""},
        { label = "Desk 6",        model = "desk6",                  desc = ""},
        { label = "Desk 7",        model = "desk7",                  desc = ""},
        { label = "Dingus",        model = "dingus",                  desc = ""},
        { label = "Crypto bro",        model = "dr_crypto",                  desc = ""},
        { label = "Dollar",        model = "dr_dollar",                  desc = ""},
        { label = "Supreme",        model = "dr_suprimo1",                  desc = ""},
        { label = "Supreme 2",        model = "dr_suprimo2",                  desc = ""},
        { label = "Supreme 3",        model = "dr_suprimo3",                  desc = ""},
        { label = "Supreme 4",        model = "dr_suprimo4",                  desc = ""},
        { label = "Supreme 5",        model = "dr_suprimo5",                  desc = ""},
        { label = "Supreme 6",        model = "dr_suprimo6",                  desc = ""},
        { label = "Supreme 7",        model = "dr_suprimo7",                  desc = ""},
        { label = "Supreme 8",        model = "dr_suprimo8",                  desc = ""},
        { label = "Escada",        model = "escada_sakurastore",                  desc = ""},
        { label = "Fish",        model = "fish_blue",                  desc = ""},
        { label = "Fish 2",        model = "fish_brown",                  desc = ""},
        { label = "Fish 3",        model = "fish_spotted",                  desc = ""},
        { label = "Kitchen",        model = "fogao_pia_cozinha",                  desc = ""},
        { label = "Kitchen 2",        model = "fogao_pia_cozinha_bordoux",                  desc = ""},
        { label = "Kitchen 3",        model = "fogao_pia_cozinha_cinza",                  desc = ""},
        { label = "Gaming Desk",        model = "gamingdesk",                  desc = ""},
        { label = "Gaming Desk 2",        model = "gamingdesk2",                  desc = ""},
        { label = "Gaming Desk 3",        model = "gamingdesk3",                  desc = ""},
        { label = "Gaming Desk 4",        model = "gamingdesk4",                  desc = ""},
        { label = "Gaming Desk 5",        model = "gamingdesk5",                  desc = ""},
        { label = "Gaming Desk 6",        model = "gamingdesk6",                  desc = ""},
        { label = "Gaming Desk 7",        model = "gamingdesk7",                  desc = ""},
        { label = "Gaming Desk 8",        model = "gamingdeskrgb",                  desc = ""},
        { label = "Guarda Roupa",        model = "guarda_roupa2",                  desc = ""},
        { label = "Guarda Roupa 2",        model = "guarda_roupa3",                  desc = ""},
        { label = "Ikea Desk",        model = "ikeadesk",                  desc = ""},
        { label = "Ikea Desk 2",        model = "ikeadesk2",                  desc = ""},
        { label = "Ikea Desk 3",        model = "ikeadesk3",                  desc = ""},
        { label = "Ikea Desk 4",        model = "ikeadesk4",                  desc = ""},
        { label = "Ikea Desk 5",        model = "ikeadesk5",                  desc = ""},
        { label = "Ikea Desk 6",        model = "ikeadesk6",                  desc = ""},
        { label = "Ikea Desk 7",        model = "ikeadesk7",                  desc = ""},
        { label = "Ikea Desk 8",        model = "ikeadesk8",                  desc = ""},
        { label = "Murm Cabinet",        model = "murm_dec_pack_cabinet",                  desc = ""},
        { label = "Murm Chair",        model = "murm_dec_pack_chair_1",                  desc = ""},
        { label = "Murm Chair 2",        model = "murm_dec_pack_chair_2",                  desc = ""},
        { label = "Murm Dresser",        model = "murm_dec_pack_dresser",                  desc = ""},
        { label = "Murm Sofa",        model = "murm_dec_pack_sofa",                  desc = ""},
        { label = "Murm Table",        model = "murm_dec_pack_table",                  desc = ""},
        { label = "Snowball Pie",        model = "np_snowball_pie",                  desc = ""},
        { label = "Gold Mask",        model = "np_squid_vip",                  desc = ""},
        { label = "Uranium Rod",        model = "np_uranium_rod",                  desc = ""},
        { label = "Bank PM",        model = "pm_bank",                  desc = ""},
        { label = "Couch",        model = "qx_ce_couch",                  desc = ""},
        { label = "Couch 2",        model = "qx_el_couch",                  desc = ""},
        { label = "Planter Bench",        model = "qx_planter_bench",                  desc = ""},
        { label = "Rectangle Couch",        model = "qx_rectangle_couch",                  desc = ""},
        { label = "Rectangle Table",        model = "qx_rectangle_table",                  desc = ""},
        { label = "Sunbed",        model = "qx_sunbed",                  desc = ""},
        { label = "Sunbed Cover",        model = "qx_sunbed_cover",                  desc = ""},
        { label = "Rabbit",        model = "rabbit_brown",                  desc = ""},
        { label = "Rabbit 2",        model = "rabbit_brown2",                  desc = ""},
        { label = "Rabbit 3",        model = "rabbit_grey",                  desc = ""},
        { label = "Rabbit 4",        model = "rabbit_red",                  desc = ""},
        { label = "Roupeiro",        model = "roupeiro_comoda",                  desc = ""},
        { label = "Torre Forno",        model = "torre_forno",                  desc = ""},
        { label = "Torre Forno 2",        model = "torre_forno_bordoux",                  desc = ""},
        { label = "Torre Forno 3",        model = "torre_forno_cinza",                  desc = ""},
        { label = "Pillow Trap",        model = "weedpillow",                  desc = ""},
        { label = "Pillow Trap 2",        model = "chromepillow",                  desc = ""},
        { label = "Pillow Trap 3",        model = "kawspillow",                  desc = ""},
        { label = "Pillow Trap 4",        model = "glopillow",                  desc = ""},
    },
    ["Miscellaneous Pack"] = {
        { label = "Carpet",        model = "atr_number_on",                  desc = ""},
        { label = "Carpet 2",        model = "atr_number_th",                  desc = ""},
        { label = "Carpet 3",        model = "atr_number_tw",                  desc = ""},
        { label = "Carpet 4",        model = "dr_carpets2",                  desc = ""},
        { label = "Carpet 5",        model = "dr_carpets3",                  desc = ""},
        { label = "Carpet 6",        model = "dr_kawssup",                  desc = ""},
        { label = "Skate Board",        model = "bam_skate_boards_01",                  desc = ""},
        { label = "Skate Board 2",        model = "bam_skate_boards_002",                  desc = ""},
        { label = "Skate Board 3",        model = "bam_skate_boards_003",                  desc = ""},
        { label = "Skate Board 4",        model = "bam_skate_boards_004",                  desc = ""},
        { label = "Plush",        model = "bbywtch_plush2",                  desc = ""},
        { label = "Beauty Kiss",        model = "beauty_kiss",                  desc = ""},
        { label = "World Cup Trophy",        model = "bv_worldcup_prop",                  desc = ""},
        { label = "Lights",        model = "bzzz_dream_of_lights_blue",                  desc = ""},
        { label = "Lights 2",        model = "bzzz_dream_of_lights_yellow",                  desc = ""},
        { label = "Lights 3",        model = "bzzz_dream_of_lights_green",                  desc = ""},
        { label = "Lights 4",        model = "bzzz_dream_of_lights_orange",                  desc = ""},
        { label = "Lights 5",        model = "bzzz_dream_of_lights_pink",                  desc = ""},
        { label = "Lights 6",        model = "bzzz_dream_of_lights_purple",                  desc = ""},
        { label = "Lights 7",        model = "bzzz_dream_of_lights_red",                  desc = ""},
        { label = "Lights 8",        model = "bzzz_dream_of_lights_white",                  desc = ""},
        { label = "Lights Lamps",        model = "bzzz_dream_of_lamps_blue",                  desc = ""},
        { label = "Lights Lamps 2",        model = "bzzz_dream_of_lamps_green",                  desc = ""},
        { label = "Lights Lamps 3",        model = "bzzz_dream_of_lamps_orange",                  desc = ""},
        { label = "Lights Lamps 4",        model = "bzzz_dream_of_lamps_pink",                  desc = ""},
        { label = "Lights Lamps 5",        model = "bzzz_dream_of_lamps_purple",                  desc = ""},
        { label = "Lights Lamps 6",        model = "bzzz_dream_of_lamps_red",                  desc = ""},
        { label = "Lights Lamps 7",        model = "bzzz_dream_of_lamps_white",                  desc = ""},
        { label = "Lights Lamps 7",        model = "bzzz_dream_of_lamps_yellow",                  desc = ""},
        { label = "Bape Bean Bag",        model = "dr_bapebeanbag",                  desc = ""},
        { label = "Pet House",        model = "casa_perro",                  desc = ""},
        { label = "Diamond YouTube",        model = "dr_diamond_yt",                  desc = ""},
        { label = "YouTube Plaque",        model = "dr_yt_plaque",                  desc = ""},
        { label = "Figure",        model = "dr_figure_01",                  desc = ""},
        { label = "Figure 2",        model = "dr_figure_02",                  desc = ""},
        { label = "Figure 3",        model = "dr_figure_03",                  desc = ""},
        { label = "Figure 4",        model = "dr_figure_04",                  desc = ""},
        { label = "Funko POP",        model = "dr_funko1",                  desc = ""},
        { label = "Funko POP 2",        model = "dr_funko2",                  desc = ""},
        { label = "Funko POP 3",        model = "dr_funko3",                  desc = ""},
        { label = "PC Gamer",        model = "dr_gamingpc",                  desc = ""},
        { label = "KAWS",        model = "dr_kaws_01",                  desc = ""},
        { label = "KAWS 2",        model = "dr_kaws_02",                  desc = ""},
        { label = "KAWS 3",        model = "dr_kaws_03",                  desc = ""},
        { label = "Ring Light",        model = "dr_ring_light",                  desc = ""},
        { label = "Rug",        model = "dr_rug1",                  desc = ""},
        { label = "Rug 2",        model = "dr_rug2",                  desc = ""},
        { label = "Rug 3",        model = "dr_rug3",                  desc = ""},
        { label = "Rug 4",        model = "dr_rug4",                  desc = ""},
        { label = "Rug 5",        model = "dr_rug5",                  desc = ""},
        { label = "Rug 6",        model = "dr_rug6",                  desc = ""},
        { label = "Rug 7",        model = "dr_rug7",                  desc = ""},
        { label = "Rug 8",        model = "dr_rug8",                  desc = ""},
        { label = "Rug 9",        model = "dr_rug9",                  desc = ""},
        { label = "Rug 10",        model = "dr_rug10",                  desc = ""},
        { label = "Rug 11",        model = "dr_rug11",                  desc = ""},
        { label = "Rug 12",        model = "dr_rug12",                  desc = ""},
        { label = "Rug 13",        model = "dr_rug13",                  desc = ""},
        { label = "Rug 14",        model = "dr_rug14",                  desc = ""},
        { label = "Rug 15",        model = "dr_rug15",                  desc = ""},
        { label = "Rug 16",        model = "dr_rug16",                  desc = ""},
        { label = "Rug 17",        model = "dr_rug17",                  desc = ""},
        { label = "Rug 18",        model = "dr_rug18",                  desc = ""},
        { label = "Rug 19",        model = "dr_rug19",                  desc = ""},
        { label = "Rug 20",        model = "dr_rug20",                  desc = ""},
        { label = "Rug 21",       model = "dr_rug21",                  desc = ""},
        { label = "Rug 22",        model = "dr_rug22",                  desc = ""},
        { label = "Rug 23",        model = "dr_rug23",                  desc = ""},
        { label = "Rug 24",        model = "dr_rug24",                  desc = ""},
        { label = "Basket Shirt Board",        model = "gabz_haters_boards001",                  desc = ""},
        { label = "Basket Shirt Board 2",        model = "gabz_haters_boards002",                  desc = ""},
        { label = "Basket Shirt Board 3",        model = "gabz_haters_boards003",                  desc = ""},
        { label = "Basket Shirt Board 4",        model = "gabz_haters_boards004",                  desc = ""},
        { label = "Basket Shirt Board 5",        model = "gabz_haters_boards005",                  desc = ""},
        { label = "Basket Shirt Board 6",        model = "gabz_haters_boards006",                  desc = ""},
        { label = "Basket Hat",        model = "gabz_haters_hat_set001",                  desc = ""},
        { label = "Basket Hat 2",        model = "gabz_haters_hat_set002",                  desc = ""},
        { label = "Basket Hat 3",        model = "gabz_haters_hat_set003",                  desc = ""},
        { label = "Basket Hat 4",        model = "gabz_haters_hat_set004",                  desc = ""},
        { label = "Basket Hat 5",        model = "gabz_haters_hat_set005",                  desc = ""},
        { label = "Basket Hat 6",        model = "gabz_haters_hat_set006",                  desc = ""},
        { label = "Basket Hat 7",        model = "gabz_haters_hat_set007",                  desc = ""},
        { label = "Basket Hat 8",        model = "gabz_haters_hat_set008",                  desc = ""},
        { label = "Basket Hat 9",        model = "gabz_haters_hat_set009",                  desc = ""},
        { label = "Basket Hat 10",        model = "gabz_haters_hat_set010",                  desc = ""},
        { label = "Basket Stand",        model = "gabz_haters_stand",                  desc = ""},
        { label = "Basket Wallracks",        model = "gabz_haters_wallracks",                  desc = ""},
        { label = "Basket Stand",        model = "gabz_haters_stand",                  desc = ""},
        { label = "Valentine Flowers",        model = "pata_freevalentinesday3",                  desc = ""},
        { label = "Vanilla Disco Pole",        model = "vanilla_disco_pole_02",                  desc = ""},
        { label = "Gaming Chair",        model = "xs_chair_01",                  desc = ""},
        { label = "Gaming Chair 2",        model = "xs_chair_02",                  desc = ""},
        { label = "Gaming Chair 3",        model = "xs_chair_03",                  desc = ""},
        { label = "Gaming Chair 4",        model = "xs_chair_04",                  desc = ""},
        { label = "Gaming Chair 5",        model = "xs_chair_05",                  desc = ""},
        { label = "Gaming Chair 6",        model = "xs_chair_06",                  desc = ""},
        { label = "Gaming Chair 7",        model = "xs_chair_07",                  desc = ""},
        { label = "Gaming Chair 8",        model = "xs_chair_08",                  desc = ""},
        { label = "Gaming Chair 9",        model = "xs_chair_09",                  desc = ""},
        { label = "Gaming Desk",        model = "xs_desk_01",                  desc = ""},
        { label = "Gaming Desk 2",        model = "xs_desk_02",                  desc = ""},
        { label = "Gaming Desk 3",        model = "xs_desk_03",                  desc = ""},
        { label = "Gaming Desk 4",        model = "xs_desk_04",                  desc = ""},
        { label = "Gaming Desk 5",        model = "xs_desk_05",                  desc = ""},
        { label = "Gaming Desk 6",        model = "xs_desk_06",                  desc = ""},
        { label = "Gaming Desk 7",        model = "xs_desk_07",                  desc = ""},
        { label = "Gaming Desk 8",        model = "xs_desk_08",                  desc = ""},
        { label = "Gaming Desk 9",        model = "xs_desk_09",                  desc = ""},
        { label = "Gaming Keyboard",        model = "xs_keyboard_01",                  desc = ""},
        { label = "Gaming Keyboard 2",        model = "xs_keyboard_02",                  desc = ""},
        { label = "Gaming Keyboard 3",        model = "xs_keyboard_03",                  desc = ""},
        { label = "Gaming Keyboard 4",        model = "xs_keyboard_04",                  desc = ""},
        { label = "Gaming Keyboard 5",        model = "xs_keyboard_05",                  desc = ""},
        { label = "Gaming Keyboard 6",        model = "xs_keyboard_06",                  desc = ""},
        { label = "Gaming Keyboard 7",        model = "xs_keyboard_07",                  desc = ""},
        { label = "Gaming Keyboard 8",        model = "xs_keyboard_08",                  desc = ""},
        { label = "Gaming Keyboard 9",        model = "xs_keyboard_09",                  desc = ""},
    },
    ["Wall/Floor Pack"] = {
        { label = "Floor",        model = "floor_01",                  desc = ""},
        { label = "Floor 2",        model = "floor_02",                  desc = ""},
        { label = "Floor 3",        model = "floor_03",                  desc = ""},
        { label = "Floor 4",        model = "floor_04",                  desc = ""},
        { label = "Pillar",        model = "pillar_a_01",                  desc = ""},
        { label = "Pillar 2",        model = "pillar_a_02",                  desc = ""},
        { label = "Pillar 3",        model = "pillar_a_03",                  desc = ""},
        { label = "Pillar 4",        model = "pillar_a_04",                  desc = ""},
        { label = "Pillar 5",        model = "pillar_a_05",                  desc = ""},
        { label = "Pillar 6",        model = "pillar_a_06",                  desc = ""},
        { label = "Pillar 7",        model = "pillar_a_07",                  desc = ""},
        { label = "Pillar 8",        model = "pillar_a_08",                  desc = ""},
        { label = "Pillar 9",        model = "pillar_a_09",                  desc = ""},
        { label = "Pillar 10",        model = "pillar_a_10",                  desc = ""},
        { label = "Wall brick",        model = "thinwall_brick",                  desc = ""},
        { label = "Wall brick 2",        model = "thinwall_brick2",                  desc = ""},
        { label = "Wall brick 3",        model = "thinwall_brick3",                  desc = ""},
        { label = "Wall brick 4",        model = "thinwall_brick4",                  desc = ""},
        { label = "Wall brick 5",        model = "thinwall_brick5",                  desc = ""},
        { label = "Wall brick 6",        model = "thinwall_brick6",                  desc = ""},
    },
}