Config = {
    requiredCops = 0,

    npcFightOnReject = false,

    account = 'money', --Options 'money', 'bank' or 'black_money'

    drugs = {
        ['weed_pooch'] = math.random(85, 370),
        ['molly_pooch'] = math.random(155, 400),
        ['spice_pooch'] = math.random(57, 100),
        ['opium_pooch'] = math.random(58, 200),
        ['shroom_pooch'] = math.random(50, 350),
        ['heroin_shot'] = math.random(52, 350),
        ['coke_pooch'] = math.random(50, 385),
        ['crack_pooch'] = math.random(98, 300),
        ['meth_pooch'] = math.random(50, 350),
        ['perc_pooch'] = math.random(170, 670),
        ['ketamine'] = math.random(100, 250),
        ['blacktar'] = math.random(100, 250),
        ['speedball'] = math.random(100, 250),
        ['flakka'] = math.random(100, 250),
        ['blonde_bundlesbox'] = math.random(148, 415),
        ['red_bodywavebox'] = math.random(148, 550),
        ['pinkremy_box'] = math.random(145, 355),
        ['lean_bottle'] = math.random(26, 300),
        ['double_cup'] = math.random(165, 430),
        ['xanax'] = math.random(187, 660),
        ['yerk30'] = math.random(50, 300),
        ['fentanyl'] = math.random(50, 200),
        ['ecstasy'] = math.random(50, 210),
        ['Famgoon_Dogfood'] = math.random(150, 450),
        -- ... add as many drugs as needed ...
    },

    salecommand1 = 'dealer', --Both sale commands do the same thing, Just give the option to have two.
    salecommand2 = 'trap',

    mincounttosell = 3,  -- Minimum count of drugs required to sell
    maxcounttosell = 5,  -- Maximum count of drugs that can be sold at once

    cityPoint = vec3(-34.556587219238, -1096.8443603516, 27.274396896362), --Set to false to disable

    zones = { -- In the zones below police will not get notified of sales
        PolyZone1 = { --BMF Block
            points = {
                vec3(-304.0, -1507.0, 30.0),
            },
            thickness = 0.0
        },
        -- ... add as many zones as needed ...
    },

    notify = {
        title = 'Illegal Sales',
        nodrugs = 'You don\'t have any drugs to sell',
        cooldown = 'Please wait some time',
        toofar = 'You\'re too far from the city',
        cops = 'There\'s no cops in the city',
        searching = 'On phone with fein for ',
        abort = 'Buyer has resigned from the order',
        notfound = 'There\'s no nearby buyess',
        approach = 'Your fein is approaching',
        found = 'You\'ve found buyer on ',
        press = 'Press [E] to make the sale.',
        reject = 'What da fuck you selling !',
        vehicle = 'You\'ve to leave vehicle to sell',
        sold = 'You\'ve sold x%s of %s for %s$',
        client = 'Your buyer ~n~~r~want\'s to buy x%s %s',
        police_notify_title = 'Police dispatch',
        police_notify_subtitle = '~r~Drugs sell',
    },

    RejectMessages = {
        'This Looks Stepped On, I\'m Good.',
        'I\'ll Pass, I Can Find Better Elsewhere.',
        'You Think I\'m a Fool? I Don\'t Want This Crap.',
        'Your Scales Must Be Off \'Cause This Is Not What I Wanted.',
        'Someone Told Me You\'re Working with 12, I\'ll Pass.',
        'I Think Someone\'s Following Me, I\'ll Come Back Later.',
        'Sorry, but I\'m not interested. I\'ve had better quality before.',
        "I appreciate the offer, but I'm looking for something stronger.",
        "No offense, but I don't trust the source. I'll find rylo or frank .",
        "I'm not feeling it today. Maybe next time.",
        "I've heard rumors about this batch rico told me . I'll stay away for now.",
        "Thanks, but I'm holding out for a higher-grade product.",
        "I don't think this is worth the price. I'll save my money.",
        "I've already got a reliable supplier 101 where it's at . Thanks anyway.",
        "I'm not interested in taking any risks right now. Maybe another time.",
        "I'm trying to lay low for a while. I'll pass on this one.",
        "This doesn't meet my expectations. I'll keep searching.",
        "I'm not in the mood for this right now. Maybe later.",
        "Sorry, but I can\'t take the risk with this product.",
        "I've had a bad experience with this before. Not interested.",
    },

    pedlist = {
        'a_f_m_beach_01',
        'a_f_m_bevhills_01',
        'a_f_m_bevhills_02',
        'a_f_m_bodybuild_01',
        'a_f_m_business_02',
        'a_f_m_downtown_01',
        'a_f_m_eastsa_01',
        'a_f_m_eastsa_02',
        'a_f_m_fatbla_01',
        'a_f_m_skidrow_01',
        'a_f_m_trampbeac_01',
        'a_f_y_indian_01',
        'a_f_y_juggalo_01',
        'a_f_y_rurmeth_01',
        'a_m_m_afriamer_01',
        'a_m_m_beach_01',
        'a_m_m_bevhills_01',
        'a_m_m_eastsa_01',
        'a_m_m_genfat_02',
        'a_m_m_hillbilly_01',
        'a_m_m_indian_01',
        'a_m_m_og_boss_01',
        'a_m_m_paparazzi_01',
        'a_m_m_malibu_01',
        'a_m_m_mexlabor_01',
        'a_m_m_polynesian_01',
        'a_m_m_rurmeth_01',
        'a_m_m_salton_01',
        'a_m_m_salton_02',
        'a_m_m_skater_01',
        'a_m_m_skidrow_01',
        'a_m_m_socenlat_01',
        'a_m_m_soucent_01',
        'a_m_m_soucent_02',
        'a_m_m_soucent_03',
        'a_m_m_soucent_04',
        'a_m_m_stlat_02',
        'a_m_m_tourist_01',
        'a_m_m_tramp_01',
        'a_m_m_trampbeac_01',
        'a_m_o_acult_02',
        'a_m_o_beach_01',
        'a_m_o_genstreet_01',
        'a_m_o_ktown_01',
        'a_m_o_soucent_03',
        'a_m_o_tramp_01',
        'a_m_y_beach_03',
        'a_m_y_beach_02',
        'a_m_y_downtown_01',
        'a_m_y_indian_01',
        'a_m_y_methhead_01',
        'a_m_y_polynesian_01',
        'a_m_y_soucent_02',
        'a_m_y_soucent_03',
        'a_m_y_stbla_01',
        'cs_lamardavis',
        'cs_stretch',
        'csb_ballasog',
        'g_f_y_ballas_01',
        'g_f_y_families_01',
        'g_m_importexport_01',
        'g_m_m_chicold_01',
        'g_m_y_armgoon_02',
        'g_m_y_ballaorig_01',
        'g_m_y_ballaeast_01',
        'g_m_y_ballasout_01',
        'g_m_y_famca_01',
        'g_m_y_lost_02',
        'g_m_y_mexgoon_03',
        'g_m_y_salvagoon_01',
        'mp_m_freemode_01',
        'mp_f_freemode_01',
        'mp_m_bogdangoon',
        'mp_m_g_vagfun_01',
        'mp_m_shopkeep_01',
        'mp_m_weed_01',
        's_m_m_ccrew_01',
        's_m_m_lifeinvad_01',
        's_m_m_linecook',
        's_m_o_busker_01',
        's_m_y_shop_mask',
        'ig_ballasog',
        'ig_car3guy2',
        'ig_claypain',
        'ig_cletus',
        'ig_djblamrupert',
        'ig_djgeneric_01',
    }
}
