Config = {}
Config.UseTruckerJob = false -- true = The shops stock is based on when truckers refill it | false = shop inventory never runs out
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.FirearmsLicenseCheck = false -- Whether a arms dealer checks for a firearms license
Config.ShopsInvJsonFile = './json/shops-inventory.json' -- json file location
Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}
Config.Products = {
 --[[    ["fishing"] = {
        [1] = {
            name = 'fishingrod',
            price = 100,
            amount = 100,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'fishingbait',
            price = 1,
            amount = 5000,
            info = {},
            type = 'item',
            slot = 2,
        }
    }, ]]
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 4,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 12,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "rolling_paper",
            price = 2,
            amount = 5000,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "eggsandwich",
            price = 5, 
            amount = 10,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "tunasandwich",
            price = 4, 
            amount = 10,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "hamsandwich",
            price = 4, 
            amount = 10,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "meteorite",
            price = 25, 
            amount = 10,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "egochaser",
            price = 2, 
            amount = 10,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "psnqs",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "bakingsoda",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 19,
        },

        [20] = {
            name = "fmdgsfjaj",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "fmdgsfjcar",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "fmdgsfjcg",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "fmdgsfjgf",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "fmdgsfjoj",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "fmdgsfjstraw",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "fmdgsfjtrop",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "fmdgsfrappebb",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "fmdgsfrappecarm",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "fmdgsfrappecchur",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "fmdgsfrappecof",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "fmdgsfrappemoc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "fmdgsfrappepep",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "fmdgsfrappepump",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "fmdgsfrappesdchoc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "fmdgsfrappesmores",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 35,
        },
        [36] = {
            name = "fmdgsfrappevan",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 36,
        },
        [37] = {
            name = "fmdgsfrappevanh",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 37,
        },
        [38] = {
            name = "fmdgsfrappewchoc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 38,
        },
        [39] = {
            name = "fmdgsbocean",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 39,
        },
        [40] = {
            name = "fmdgsbpure",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 40,
        },
        [41] = {
            name = "fmdgsbpurel",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 41,
        },
        [42] = {
            name = "fmdgsbpurep",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 42,
        },
        [43] = {
            name = "fmdgsbpures",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 43,
        },
        [44] = {
            name = "fmdgscantifaa",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 44,
        },
        [45] = {
            name = "fmdgscantifab",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 45,
        },
        [46] = {
            name = "fmdgscantifac",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 46,
        },
        [47] = {
            name = "fmdgscantifafp",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 47,
        },
        [48] = {
            name = "fmdgscantifag",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 48,
        },
        [49] = {
            name = "fmdgscantifaga",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 49,
        },
        [50] = {
            name = "fmdgscantifagf",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 50,
        },
        [51] = {
            name = "fmdgscantifam",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 51,
        },
        [52] = {
            name = "fmdgscantifaoz",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 52,
        },
        [53] = {
            name = "fmdgscantifap",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 53,
        },
        [54] = {
            name = "fmdgscantifapc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 54,
        },
        [55] = {
            name = "fmdgscantifas",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 55,
        },
        [56] = {
            name = "fmdgscvalley",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 56,
        },
        [57] = {
            name = "fmdgssebrc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 57,
        },
        [58] = {
            name = "fmdgssefp",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 58,
        },
        [59] = {
            name = "fmdgssefp",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 59,
        },
        [60] = {
            name = "fmdgssegz",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 60,
        },
        [61] = {
            name = "fmdgssell",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 61,
        },
        [62] = {
            name = "fmdgssembz",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 62,
        },
        [63] = {
            name = "fmdgsseoz",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 63,
        },
        [64] = {
            name = "fmdgssesl",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 64,
        },
        [65] = {
            name = "fmdgssetb",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 65,
        },
        [66] = {
            name = "fmdgssews",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 66,
        },
        [67] = {
            name = "fmdgsrecharge",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 67,
        },
        [68] = {
            name = "fmdgslabsbbq",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 68,
        },
        [69] = {
            name = "fmdgslabsog",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 69,
        },
        [70] = {
            name = "fmdgslabswavy",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 70,
        },
        [71] = {
            name = "fmdgsoritosbuff",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 71,
        },
        [72] = {
            name = "fmdgsoritosbuffm",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 72,
        },
        [73] = {
            name = "fmdgsoritoscheese",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 73,
        },
        [74] = {
            name = "fmdgsoritoscool",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 74,
        },
        [75] = {
            name = "fmdgsoritoscorn",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 75,
        },
        [76] = {
            name = "fmdgsoritosguac",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 76,
        },
        [77] = {
            name = "fmdgsoritosjap",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 77,
        },
        [78] = {
            name = "fmdgsoritosnacho",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 78,
        },
        [79] = {
            name = "fmdgsoritospickle",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 79,
        },
        [80] = {
            name = "fmdgsoritosribs",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 80,
        },
        [81] = {
            name = "fmdgsoritossnacho",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 81,
        },
        [82] = {
            name = "fmdgsoritossweetc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 82,
        },
        [83] = {
            name = "fmdgsoritostacoex",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 83,
        },
        [84] = {
            name = "fmdgsrafflesad",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 84,
        },
        [85] = {
            name = "fmdgsrafflesbaked",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 85,
        },
        [86] = {
            name = "fmdgsrafflesbbq",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 86,
        },
        [87] = {
            name = "fmdgsrafflesbbqd",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 87,
        },
        [88] = {
            name = "fmdgsrafflesog",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 88,
        },
        [89] = {
            name = "fmdgsrafflesqueso",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 89,
        },
        [90] = {
            name = "fmdgscheezee",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 90,
        },
        [91] = {
            name = "fmdgscookiemanstan",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 91,
        },
        [92] = {
            name = "fmdgsgummybear",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 92,
        },
        [93] = {
            name = "fmdgsmfncookies",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 93,
        },
        [94] = {
            name = "fmdgsrafflesog",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 94,
        },
        [95] = {
            name = "fmdgspretzels",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 95,
        },
        [96] = {
            name = "fmdgspronglescc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 96,
        },
        [97] = {
            name = "fmdgspronglesog",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 97,
        },
        [98] = {
            name = "fmdgspronglessco",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 98,
        },
        [99] = {
            name = "fmdgspuffscolors",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 99,
        },
        [100] = {
            name = "fmdgspuffspretzels",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 100,
        },
        [101] = {
            name = "fmdgspuffsprincess",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 101,
        },
        [102] = {
            name = "fmdgscookiesb",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 102,
        },
        [103] = {
            name = "fmdgscookiescc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 103,
        },
        [104] = {
            name = "fmdgscookiesdc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 104,
        },
        [105] = {
            name = "fmdgscookiesmc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 105,
        },
        [106] = {
            name = "fmdgscookiesmic",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 106,
        },
        [107] = {
            name = "fmdgscookiess",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 107,
        },
        [108] = {
            name = "fmdgscookiesg",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 108,
        },
        [109] = {
            name = "fmdgsramenb",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 109,
        },
        [110] = {
            name = "fmdgsramenc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 110,
        },
        [111] = {
            name = "fmdgsramens",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 111,
        },
        [112] = {
            name = "fmdgsicecream",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 112,
        },
        [113] = {
            name = "fmdgsicecreamp",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 113,
        },
        [114] = {
            name = "fmdgsicecreamc",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 114,
        },
        [115] = {
            name = "fmdgspizzac",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 115,
        },
        [116] = {
            name = "fmdgspizzap",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 116,
        },
        [117] = {
            name = "fmdgspizzas",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 117,
        },
        [118] = {
            name = "fmdgshdog",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 118,
        },
        [119] = {
            name = "fmdgsbdaykrispies",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 119,
        },
        [120] = {
            name = "fmdgsbitterfinga",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 120,
        },
        [121] = {
            name = "fmdgsgoodday",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 121,
        },
        [122] = {
            name = "fmdgsmillymay",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 122,
        },
        [123] = {
            name = "fmdgscranch",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 123,
        },
        [124] = {
            name = "fmdgskeekat",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 124,
        },
        [125] = {
            name = "fmdgstwin",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 125,
        },
        [126] = {
            name = "fmdgshereheis",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 126,
        },
        [127] = {
            name = "fmdgsfru2go",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 127,
        },
        [128] = {
            name = "fmdgsfru2goru",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 128,
        },
        [129] = {
            name = "fmdgsbrownie",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 129,
        },
        [130] = {
            name = "fmdgsbrowniec",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 130,
        },
        [131] = {
            name = "fmdgschoccpie",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 131,
        },
        [132] = {
            name = "fmdgsfudgepie",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 132,
        },
        [133] = {
            name = "fmdgsoatpie",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 133,
        },
        [134] = {
            name = "fmdgsstarcrunch",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 134,
        },
        [135] = {
            name = "fmdgszebracake",
            price = 1, 
            amount = 10,
            info = {},
            type = "item",
            slot = 135,
        },
        





































    },
    ["liquor"] = {
        [1] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 12,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "beer_am",
            price = 8, 
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "beer_logger",
            price = 9, 
            amount = 10,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "beer_piss",
            price = 6, 
            amount = 10,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer_dusche",
            price = 7, 
            amount = 10,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "beer_patriot",
            price = 8, 
            amount = 10,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "beer_stz",
            price = 6, 
            amount = 10,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "beer_pride",
            price = 7, 
            amount = 10,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "beer_bar",
            price = 9, 
            amount = 10,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "beer_jakey",
            price = 5, 
            amount = 10,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "beer_bar",
            price = 7, 
            amount = 10,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "beer_blr",
            price = 8, 
            amount = 10,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "whiskey_mount",
            price = 15, 
            amount = 10,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "whiskey_richards",
            price = 18, 
            amount = 10,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "whiskey_macbeth",
            price = 14, 
            amount = 10,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "whiskey_richards",
            price = 18, 
            amount = 10,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "rum",
            price = 13, 
            amount = 10,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "tequila",
            price = 16, 
            amount = 10,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "brandy_cardi",
            price = 11, 
            amount = 10,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "brandy_cognac",
            price = 17, 
            amount = 10,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "wine_red",
            price = 8, 
            amount = 10,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "wine_rose",
            price = 9, 
            amount = 10,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "wine_white",
            price = 7, 
            amount = 10,
            info = {},
            type = "item",
            slot = 25,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "repairkit",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
            requiredJob = { "mechanic", "police" }
        },
        [5] = {
            name = "screwdriverset",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "phone",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "radio",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "firework1",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "firework2",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "firework3",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "firework4",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "bddrone",
            price = 756,
            amount = 2,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "cleaningkit",
            price = 150,
            amount = 150,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "advancedrepairkit",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = { "mechanic" }
        },
        [16] = {
            name = "camviewer",
            price = 729,
            amount = 150,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "360cctv",
            price = 496,
            amount = 150,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "cctv",
            price = 250,
            amount = 150,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "rccar",
            price = 230,
            amount = 10,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "bdrone",
            price = 399,
            amount = 1,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "badrone",
            price = 499,
            amount = 1,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "bbdrone",
            price = 599,
            amount = 5,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "bcdrone",
            price = 699,
            amount = 5,
            info = {},
            type = "item",
            slot = 24,
        },
    },
    ["weedshop"] = {
        [1] = {
            name = "joint",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_poolcue",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weed_nutrition",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "empty_weed_bag",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "rolling_paper",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "plastic_baggy",
            price = 5,
            amount = 1000,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "water_can",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 7,
        },
        
        --[[ [8] = {
            name = "hydrochloric_acid",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "sodium_hydroxide",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "sulfuric_acid",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "methkey",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 11,
        }, ]]
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["leisureshop"] = {
        [1] = {
            name = "parachute",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "diving_fill",
            price = 500,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        -- [4] = {
        --     name = "smoketrailred",
        --     price = 250,
        --     amount = 50,
        --     info = {},
        --     type = "item",
        --     slot = 4,
        -- },
    },
    ["weapons"] = {
        [1] = {
            name = "weapon_knife",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_bat",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hatchet",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
            requiredJob = { "mechanic", "police" }
        },
        [4] = {
            name = "weapon_pistol",
            price = 100500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
            requiresLicense = false
        },
        [5] = {
            name = "weapon_snspistol",
            price = 45000,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
            requiresLicense = false
        },
        [6] = {
            name = "weapon_vintagepistol",
            price = 70000,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
            requiresLicense = false
        },
        [7] = {
            name = "pistol_ammo",
            price = 650,
            amount = 250,
            info = {},
            type = "item",
            slot = 7,
          --  requiresLicense = false
        },
        [8] = { 
            name = "weapon_g26",
            price = 120000,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
          --  requiresLicense = false
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
 --[[ Removed. Rockstar and FiveM Terms of service changed. can't use real life brands
    ["mcdonalds"] = {
        [1] = {
            name = 'bigmac',
            price = 4,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'mcchicken',
            price = 3,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'quarterpounder',
            price = 5,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        },
        [4] = {
            name = 'dquarterpounder',
            price = 6,
            amount = 50,
            info = {},
            type = 'item',
            slot = 4,
        },
        [5] = {
            name = 'filet-o-fish',
            price = 4,
            amount = 50,
            info = {},
            type = 'item',
            slot = 5,
        },
        [6] = {
            name = 'bigmac_meal',
            price = 7,
            amount = 150,
            info = {},
            type = 'item',
            slot = 6,
        },
        [7] = {
            name = 'mcchicken_meal',
            price = 7,
            amount = 150,
            info = {},
            type = 'item',
            slot = 7,
        },
        [8] = {
            name = 'quarterpounder_meal',
            price = 8,
            amount = 150,
            info = {},
            type = 'item',
            slot = 8,
        },
        [9] = {
            name = 'dquarterpounder_meal',
            price = 9,
            amount = 150,
            info = {},
            type = 'item',
            slot = 9,
        },
        [10] = {
            name = 'filet-o-fish_meal',
            price = 8,
            amount = 150,
            info = {},
            type = 'item',
            slot = 10,
        },
        [11] = {
            name = 'cheeseburger',
            price = 2,
            amount = 50,
            info = {},
            type = 'item',
            slot = 11,
        },
        [12] = {
            name = 'dcheeseburger',
            price = 3,
            amount = 50,
            info = {},
            type = 'item',
            slot = 12,
        },
        [13] = {
            name = 'tcheeseburger',
            price = 2,
            amount = 50,
            info = {},
            type = 'item',
            slot = 13,
        },
        [14] = {
            name = 'sfries',
            price = 1,
            amount = 30,
            info = {},
            type = 'item',
            slot = 14,
        },
        [15] = {
            name = 'mfries',
            price = 2,
            amount = 50,
            info = {},
            type = 'item',
            slot = 15,
        },
        [16] = {
            name = 'cheeseburger_meal',
            price = 4,
            amount = 150,
            info = {},
            type = 'item',
            slot = 16,
        },
        [17] = {
            name = 'dcheeseburger_meal',
            price = 5,
            amount = 150,
            info = {},
            type = 'item',
            slot = 17,
        },
        [18] = {
            name = 'tcheeseburger_meal',
            price = 5,
            amount = 150,
            info = {},
            type = 'item',
            slot = 18,
        },
        [19] = {
            name = 'lfries',
            price = 2,
            amount = 70,
            info = {},
            type = 'item',
            slot = 19,
        },
        [20] = {
            name = 'cocacola',
            price = 1,
            amount = 50,
            info = {},
            type = 'item',
            slot = 20,
        },
        [21] = {
            name = '6pnuggets',
            price = 3,
            amount = 50,
            info = {},
            type = 'item',
            slot = 21,
        },
        [22] = {
            name = '10pnuggets',
            price = 5,
            amount = 50,
            info = {},
            type = 'item',
            slot = 22,
        },
        [23] = {
            name = '20pnuggets',
            price = 10,
            amount = 50,
            info = {},
            type = 'item',
            slot = 23,
        },
        [24] = {
            name = 'sscone',
            price = 1,
            amount = 20,
            info = {},
            type = 'item',
            slot = 24,
        },
        [25] = {
            name = 'ssconef',
            price = 1,
            amount = 20,
            info = {},
            type = 'item',
            slot = 25,
        },
        [26] = {
            name = '6pnuggets_meal',
            price = 7,
            amount = 150,
            info = {},
            type = 'item',
            slot = 26,
        },
        [27] = {
            name = '10pnuggets_meal',
            price = 8,
            amount = 150,
            info = {},
            type = 'item',
            slot = 27,
        },
        [28] = {
            name = '20pnuggets_meal',
            price = 12,
            amount = 150,
            info = {},
            type = 'item',
            slot = 28,
        },
        [29] = {
            name = 'mflurryo',
            price = 2,
            amount = 50,
            info = {},
            type = 'item',
            slot = 29,
        },
        [30] = {
            name = 'mflurrym',
            price = 3,
            amount = 50,
            info = {},
            type = 'item',
            slot = 30,
        },
        [31] = {
            name = 'hotapplepie',
            price = 1,
            amount = 20,
            info = {},
            type = 'item',
            slot = 31,
        },
    },]]
    ["huntingshop"] = {
        [1] = {
            name = 'weapon_sniperrifle2',
            price = 1500,
            amount = 10,
            info = {},
            type = 'weapon',
            slot = 1,
            requiresLicense = false
        },
        [2] = {
            name = 'snp_ammo',
            price = 100,
            amount = 50,
            info = {},
            type = 'item',
            slot = 2,
            requiresLicense = false
        },
        [3] = {
            name = 'huntingbait',
            price = 150,
            amount = 150,
            info = {},
            type = 'item',
            slot = 3
        },
        [4] = {
            name = 'weapon_knife',
            price = 500,
            amount = 50,
            info = {},
            type = 'item',
            slot = 4
        }
    },
    ["skateboard"] = {
        [1] = {
            name = 'skateboard',
            price = 300,
            amount = 10,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
}
Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(26.45, -1315.51, 29.62, 0.07)
    },
    

    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(379.97, 357.3, 102.56, 26.42)
    },
    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-15.916481018066406,-1478.808837890625,30.6278076171875,99.21259307861328),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-15.916481018066406,-1478.808837890625,30.6278076171875,99.21259307861328)
    },

    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-41.91, -1784.46, 29.13, 321.85),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-41.91, -1784.46, 29.13, 321.85)
    },

    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-42.738460540771484,-1774.931884765625,29.111328125,59.52755355834961),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-54.751644134521484,-1780.2197265625,28.993408203125,79.37007904052734)
    },

    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(826.7077026367188, -2152.892333984375, 28.926025390625, 85.03936767578125),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(4.958241939544678,-1105.6614990234375,29.094482421875,249.44882202148438),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(978.46, 39.07, 74.88, 64.0),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = false,
        ["blipsprite"] = 617,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(972.6, 9.22, 81.04, 233.38)
    },

    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(968.13, 29.85, 74.88, 208.86),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(937.16, 1.0, 78.76, 152.4)
    },

    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1162.13, -1568.57, 4.39, 328.52)
    },

    -- Sea Word Locations
    ["seaword"] = {
        ["label"] = "Sea Word",
        ["coords"] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish",
        ["targetLabel"] = "Sea Word",
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1674.18, -1073.7, 13.15, 333.56)
    },

    -- Leisure Shop Locations
    ["leisureshop"] = {
        ["label"] = "Leisure Shop",
        ["coords"] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    --- New 
    ["247supermarketn1"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(240.1431, -897.5628, 29.6232, 153.8666),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0,
        ["delivery"] = vector4(240.1431, -897.5628, 29.6232, 153.8666)
    },
     --[[ Removed. Rockstar and FiveM Terms of services changed. can't use real life brands
    ["mcdonalds"] = {
        ["label"] = "McDonalds",
        ["coords"] = vector4(90.56, 285.77, 110.22, 69.58),
        ["ped"] = 's_f_y_factory_01',
        ["scenario"] = "WORLD_LOOKAT_POINT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Order McDonalds",
        ["products"] = Config.Products["mcdonalds"],
        ["showblip"] = true,
        ["blipsprite"] = 78,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 46,
        ["delivery"] = vector4(90.56, 285.77, 110.22, 69.58)
    }, ]]
    ["huntingshop"] = {
        ["label"] = "Hunting Shop",
        ["coords"] = vector4(-674.5170, 5837.8423, 17.3401, 129.6320),
        ["ped"] = 'ig_hunter',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Order McDonalds",
        ["products"] = Config.Products["huntingshop"],
        ["showblip"] = true,
        ["blipsprite"] = 463,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 46,
        ["delivery"] = vector4(-674.5170, 5837.8423, 17.3401, 129.6320)
    },
   --[[  -- My Fishing Shop
    ["fishingshop"] = {
        ["label"] = "The Fish Shop",
        ["coords"] = vector4(-1597.9, 5201.15, 4.39, 69.79),
        ["ped"] = 's_m_m_migrant_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish-fins",
        ["targetLabel"] = "Open Fishing Store",
        ["products"] = Config.Products["fishing"],
        ["showblip"] = true,
        ["blipsprite"] = 68,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 38,
        ["delivery"] = vector4(-1597.9, 5201.15, 4.39, 69.79)
    }, ]]
    ["skateboardshop"] = {
        ["label"] = "The Skateboard Shop",
        ["coords"] = vector4(-1369.9000, -522.7589, 30.4695, 35.6665),
        ["ped"] = 'ig_bride',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Skateboard Store",
        ["products"] = Config.Products["skateboard"],
        ["showblip"] = true,
        ["blipsprite"] = 348,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 43,
        ["delivery"] = vector4(-1369.9000, -522.7589, 30.4695, 35.6665)
    },

}
