Config = {}

Config.WeapDraw = {
    variants = { 130, 122, 3, 6, 8 },
    weapons = {
        'WEAPON_PISTOL',
        'WEAPON_PISTOL_MK2',
        'WEAPON_COMBATPISTOL',
        'WEAPON_APPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_REVOLVER',
        'WEAPON_SNSPISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_VINTAGEPISTOL',




        -- Melee
    'weapon_dagger',
    'weapon_bat',
    'weapon_bottle',
    'weapon_crowbar',
    'weapon_golfclub',
    'weapon_hammer',
    'weapon_hatchet',
    'weapon_knuckle',
    'weapon_knife',
    'weapon_machete',
    'weapon_switchblade',
    'weapon_wrench',
    'weapon_battleaxe',
    'weapon_poolcue',
    'weapon_briefcase',
    'weapon_briefcase_02',
    'weapon_garbagebag',
    'weapon_handcuffs',
    'weapon_bread',
    'weapon_stone_hatchet',

    -- Handguns
    'weapon_pistol',
    'weapon_pistol_mk2',
    'weapon_pistolxm3',
    'weapon_combatpistol',
    'weapon_appistol',
    'weapon_pistol50',
    'weapon_snspistol',
    'weapon_heavypistol',
    'weapon_vintagepistol',
    'weapon_flaregun',
    'weapon_marksmanpistol',
    'weapon_revolver',
    'weapon_revolver_mk2',
    'weapon_doubleaction',
    'weapon_snspistol_mk2',
    'weapon_raypistol',
    'weapon_ceramicpistol',
    'weapon_navyrevolver',
    'weapon_gadgetpistol',

    -- Submachine Guns
    'weapon_microsmg',
    'weapon_smg',
    'weapon_smg_mk2',
    'weapon_assaultsmg',
    'weapon_combatpdw',
    'weapon_machinepistol',
    'weapon_minismg',
    'weapon_raycarbine',

    -- Shotguns
    'weapon_pumpshotgun',
    'weapon_sawnoffshotgun',
    'weapon_assaultshotgun',
    'weapon_bullpupshotgun',
    'weapon_musket',
    'weapon_heavyshotgun',
    'weapon_dbshotgun',
    'weapon_autoshotgun',
    'weapon_pumpshotgun_mk2',
    'weapon_combatshotgun',

    -- Assault Rifles
    'weapon_assaultrifle',
    'weapon_assaultrifle_mk2',
    'weapon_carbinerifle',
    'weapon_carbinerifle_mk2',
    'weapon_tacticalrifle',
    'weapon_advancedrifle',
    'weapon_specialcarbine',
    'weapon_bullpuprifle',
    'weapon_compactrifle',
    'weapon_specialcarbine_mk2',
    'weapon_bullpuprifle_mk2',
    'weapon_militaryrifle',
    'weapon_heavyrifle',

    -- Light Machine Guns
    'weapon_mg',
    'weapon_combatmg',
    'weapon_gusenberg',
    'weapon_combatmg_mk2',

    -- Sniper Rifles
    'weapon_sniperrifle',
    'weapon_heavysniper',
    'weapon_marksmanrifle',
    'weapon_remotesniper',
    'weapon_heavysniper_mk2',
    'weapon_marksmanrifle_mk2',

    -- Heavy Weapons
    'weapon_rpg',
    'weapon_grenadelauncher',
    'weapon_grenadelauncher_smoke',
    'weapon_emplauncher',
    'weapon_minigun',
    'weapon_firework',
    'weapon_railgun',
    'weapon_hominglauncher',
    'weapon_compactlauncher',
    'weapon_rayminigun',

    -- Throwables
    'weapon_grenade',
    'weapon_bzgas',
    'weapon_molotov',
    'weapon_stickybomb',
    'weapon_proxmine',
    'weapon_snowball',
    'weapon_pipebomb',
    'weapon_ball',
    'weapon_smokegrenade',
    'weapon_flare',

    
    'weapon_petrolcan',
    'weapon_fireextinguisher',
    'weapon_hazardcan',
    'weapon_fertilizercan',

    -- Custom Weapons NoobySloth (it is possible that some weapon is broken)
    -- ref: https://github.com/NoobySloth/Custom-Weapons
    'weapon_ak47',
    'weapon_de',
    'weapon_fnx45',
    'weapon_glock17',
    'weapon_m4',
    'weapon_hk416',
    'weapon_mk14',
    'weapon_m110',
    'weapon_huntingrifle',
    'weapon_ar15',
    'weapon_m9',
    'weapon_m70',
    'weapon_m1911',
    'weapon_mac10',
    'weapon_uzi',
    'weapon_mp9',
    'weapon_mossberg',
    'weapon_remington',
    'weapon_scarh',
    'weapon_shiv',
    'weapon_katana',
    'weapon_sledgehammer',
    'weapon_mp5',
    'weapon_glock18c',
    'weapon_glock22',
    'weapon_aks74',
    'weapon_ak74',



    -- KYROS WEAPON PACK V5
    'weapon_bar15',
    'weapon_axe',
    'weapon_blackarp',
    'weapon_bscar',
    'weapon_thompson',
    'weapon_blueglocks',
    'weapon_chair',
    'weapon_dmk18',
    'weapon_fn57',
    'weapon_glock21',
    'weapon_glock41',
    'weapon_glockbeams',
    'weapon_p30l',
    'weapon_illglock17',
    'weapon_krissvector',
    'weapon_lbtarp',
    'weapon_mgglock',
    'weapon_midasglock',
    'weapon_m500',
    'weapon_p210',
    'weapon_ram7',
    'weapon_redarp',
    'weapon_redm4a1',
    'weapon_r590',
    'weapon_sr40',
    'weapon_t1911',
    'weapon_tarp',
    'weapon_tglock19',
    'weapon_tec9s',
    'weapon_woarp',


    -- KYROS WEAPON PACK V4
    'weapon_glock19x',
    'weapon_glock19',
    'weapon_glock40',
    'weapon_glock40s',
    'weapon_ddm4v5',
    'weapon_mpx',
    'weapon_pd509',
    'weapon_aps',
    'weapon_ppk',
    'weapon_pitviper',
    'weapon_barp',
    'weapon_rdp',
    'weapon_lok',
    'weapon_plr',
    'weapon_xds9',
    'weapon_pps',
    'weapon_xdme',
    'weapon_sp',
    'weapon_glock17s',
    'weapon_glock18c',
    'weapon_glock19s',
    'weapon_arpistol',
    'weapon_glock26s',
    'weapon_grenades',
    'weapon_m32s',
    'weapon_microdraco',
    'weapon_ruger57',
    'weapon_mk18',
    'weapon_680',
    'weapon_ziptie',
    -- KYROS WEAPON PACK V3
    'weapon_m32',
    "weapon_ddm4v7",
    "weapon_g2c",
    "weapon_pmr",
    "weapon_g19g4",
    "weapon_gs",
    "weapon_sp320",
    "weapon_bp",
    "weapon_tglock",
    "weapon_g19x",
    "weapon_awp",
    "weapon_tuzi",
    "weapon_broom",
    "weapon_tomahawk",
    "weapon_tridagger",
    "weapon_shammer",
    "weapon_dildo",
    "weapon_uk",
    "weapon_sd",
    "weapon_m200",
    "weapon_scar",
    "weapon_552",
    "weapon_l1a1",
    "weapon_fal",
    "weapon_mcx",
    "weapon_p2011",
    "weapon_p416",
    "weapon_hipoint",
    "weapon_de",
    "weapon_auga1",
    "weapon_p90",
    "weapon_vesper",
    "weapon_h12",
    "weapon_g26",
    "weapon_ia2",
    "weapon_as50",
    "weapon_jrbak",
    "weapon_neva",
    "weapon_howa_2",
    "weapon_glacier",
    "weapon_anarchy",
    "weapon_art64",
    "weapon_autosmg",
    "WEAPON_BAS_P_RED",
    "CZ Scorpion EVO",
    "weapon_galilar",











    
    }
}
