resource_manifest_version "44febabe-d386-4d18-afbe-5e627f4af937"

files {
  'audio/sfx/resident/ambience.awc',
  'audio/sfx/resident/animals_footsteps.awc',
  'audio/sfx/resident/collision.awc',
  'audio/sfx/resident/collisions.awc',
  'audio/sfx/resident/doors.awc',
  'audio/sfx/resident/explosions.awc',
  'audio/sfx/resident/feet_materials.awc',
  'audio/sfx/resident/feet_resident.awc',
  'audio/sfx/resident/frontend.awc',
  'audio/sfx/resident/low_latency.awc',
  'audio/sfx/resident/melee.awc',
  'audio/sfx/resident/movement.awc',
  'audio/sfx/resident/player_switch.awc',
  'audio/sfx/resident/weapons.awc',
  'audio/sfx/resident/vehicles.awc',
  'audio/sfx/resident/weather.awc',

  'audio/sfx/streamed_vehicles/4_cylinder_saloon_1.awc',
  'audio/sfx/streamed_vehicles/4_cylinder_sport_1.awc',
  'audio/sfx/streamed_vehicles/4x4.awc',
  'audio/sfx/streamed_vehicles/600_streetbike.awc',
  'audio/sfx/streamed_vehicles/1000_racebike.awc',
  'audio/sfx/streamed_vehicles/blimp.awc',
  'audio/sfx/streamed_vehicles/box_van_1.awc',
  'audio/sfx/streamed_vehicles/box_van_3.awc',
  'audio/sfx/streamed_vehicles/cargo_jet.awc',
  'audio/sfx/streamed_vehicles/cargobob_helicopter.awc',
  'audio/sfx/streamed_vehicles/chopper_1.awc',
  'audio/sfx/streamed_vehicles/chopper_2.awc',
  'audio/sfx/streamed_vehicles/chopper_3.awc',
  'audio/sfx/streamed_vehicles/dinghy.awc',
  'audio/sfx/streamed_vehicles/duster.awc',
  'audio/sfx/streamed_vehicles/dodo.awc',
  'audio/sfx/streamed_vehicles/fast_1.awc',
  'audio/sfx/streamed_vehicles/fast_2.awc',
  'audio/sfx/streamed_vehicles/fast_3.awc',
  'audio/sfx/streamed_vehicles/fast_4.awc',
  'audio/sfx/streamed_vehicles/forklift.awc',
  'audio/sfx/streamed_vehicles/generic_helicopter.awc',
  'audio/sfx/streamed_vehicles/golf_kart.awc',
  'audio/sfx/streamed_vehicles/hatchback_1.awc',
  'audio/sfx/streamed_vehicles/hatchback_2.awc',
  'audio/sfx/streamed_vehicles/hunter_helicopter.awc',
  'audio/sfx/streamed_vehicles/hybrid.awc',
  'audio/sfx/streamed_vehicles/jet.awc',
  'audio/sfx/streamed_vehicles/large_jet.awc',
  'audio/sfx/streamed_vehicles/lazer.awc',
  'audio/sfx/streamed_vehicles/luxury_car_1.awc',
  'audio/sfx/streamed_vehicles/mammatus.awc',
  'audio/sfx/streamed_vehicles/marquis_sailboat.awc',
  'audio/sfx/streamed_vehicles/military_helicopter.awc',
  'audio/sfx/streamed_vehicles/moped.awc',
  'audio/sfx/streamed_vehicles/muscle_car_1.awc',
  'audio/sfx/streamed_vehicles/muscle_car_2.awc',
  'audio/sfx/streamed_vehicles/muscle_car_3.awc',
  'audio/sfx/streamed_vehicles/muscle_car_4.awc',
  'audio/sfx/streamed_vehicles/rally_racer.awc',
  'audio/sfx/streamed_vehicles/rc_motor.awc',
  'audio/sfx/streamed_vehicles/regular_saloon_1.awc',
  'audio/sfx/streamed_vehicles/rig_1.awc',
  'audio/sfx/streamed_vehicles/rig_2.awc',
  'audio/sfx/streamed_vehicles/rig_3.awc',
  'audio/sfx/streamed_vehicles/scorcher.awc',
  'audio/sfx/streamed_vehicles/sanchez.awc',
  'audio/sfx/streamed_vehicles/shamal.awc',
  'audio/sfx/streamed_vehicles/stunt.awc',
  'audio/sfx/streamed_vehicles/sub_creaks.awc',
  'audio/sfx/streamed_vehicles/supercar_1.awc',
  'audio/sfx/streamed_vehicles/supercar_2.awc',
  'audio/sfx/streamed_vehicles/test_synth_sports.awc',
  'audio/sfx/streamed_vehicles/test_wagon_agent.awc',
  'audio/sfx/streamed_vehicles/titan.awc',
  'audio/sfx/streamed_vehicles/tractor_1.awc',
  'audio/sfx/streamed_vehicles/tractor_2.awc',
  'audio/sfx/streamed_vehicles/trawler.awc',
  'audio/sfx/streamed_vehicles/v_style_1.awc',
  'audio/sfx/streamed_vehicles/v_style_2.awc',
  'audio/sfx/streamed_vehicles/v_style_3.awc',
  'audio/sfx/streamed_vehicles/v_style_4.awc',
  'audio/sfx/streamed_vehicles/v8_luxury_1.awc',
  'audio/sfx/streamed_vehicles/velum.awc',
  'audio/sfx/streamed_vehicles/vulkan.awc',

  'audio/sfx/streamed_vehicles_low_latency/cargobob.awc',
  'audio/sfx/streamed_vehicles_low_latency/generic.awc',
  'audio/sfx/streamed_vehicles_low_latency/helicopter.awc',
  'audio/sfx/streamed_vehicles_low_latency/hunter.awc',
  'audio/sfx/streamed_vehicles_low_latency/military.awc',

  'audio/sfx/weapons_player/lmg_combat.awc',
  'audio/sfx/weapons_player/lmg_mg_player.awc',
  'audio/sfx/weapons_player/mgn_sml_am83_vera.awc',
  'audio/sfx/weapons_player/mgn_sml_am83_verb.awc',
  'audio/sfx/weapons_player/mgn_sml_sc__l.awc',
  'audio/sfx/weapons_player/ptl_50cal.awc',
  'audio/sfx/weapons_player/ptl_combat.awc',
  'audio/sfx/weapons_player/ptl_pistol.awc',
  'audio/sfx/weapons_player/ptl_px4.awc',
  'audio/sfx/weapons_player/ptl_rubber.awc',
  'audio/sfx/weapons_player/sht_bullpup.awc',
  'audio/sfx/weapons_player/sht_pump.awc',
  'audio/sfx/weapons_player/smg_micro.awc',
  'audio/sfx/weapons_player/smg_smg.awc',
  'audio/sfx/weapons_player/snp_heavy.awc',
  'audio/sfx/weapons_player/snp_rifle.awc',
  'audio/sfx/weapons_player/spl_grenade_player.awc',
  'audio/sfx/weapons_player/spl_minigun_player.awc',
  'audio/sfx/weapons_player/spl_prog_ar_player.awc',
  'audio/sfx/weapons_player/spl_railgun.awc',
  'audio/sfx/weapons_player/spl_rpg_player.awc',
  'audio/sfx/weapons_player/spl_tank_player.awc',
}

data_file 'AUDIO_WAVEPACK' 'audio/sfx/resident'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/weapons_player'

data_file 'AUDIO_WAVEPACK' 'audio/sfx/streamed_vehicles'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/streamed_vehicles_low_latency'