Strings = {
    player_in_vehicle = 'Suspect In Vehicle',
    player_in_vehicle_desc = 'Remove the suspect from the vehicle before doing this!',
    suspect_died_escort = 'Suspect Died',
    suspect_died_escort_desc = 'The suspect died while escorting and you dropped them.',


    stop_escorting_interact = '[E] - Stop Escorting',
    cant_wield = 'Cannot Equip',
    cant_wield_desc = 'You cannot use this at this time!',



    jailed_player = 'Jailed Suspect',
    jailed_player_desc = 'You have jailed %s for %s months.',

    gps_active = 'GPS Activated',
    gps_active_desc = 'Player %s activated their GPS',
    gps_deactive = 'GPS Deactivated',
    gps_deactive_desc = 'Player %s deactivated their GPS',

    no_wsb = '^0[^3WARNING^0] wasabi_bridge was NOT started AFTER framework and/or BEFORE resource: %s',
    currency = '$',
    success = 'Success',
    go_back = '< Go Back',
    cloakroom = 'Cloakroom',
    civilian_wear = 'Civilian Wear',
    armoury_quantity_dialog = 'Quantity To Order',
    quantity = 'Quantity',
    invalid_amount = 'Invalid Amount',
    invalid_amount_desc = 'Please enter a valid amount',
    successful_purchase_desc = 'You have successfully ordered your weapons from the armoury',
    lacking_funds = 'Lacking Funds',
    lacking_funds_desc = 'You are lacking funds in the bank for this purchase',
    no_permission = 'No Permission',
    no_access_desc = 'You do not have authorization to access this!',
    key_map_cuff = 'Handcuff Player',
    key_map_tackle = 'Tackle player while sprinting',
    key_map_job = 'Open Job Menu',
    no_nearby = 'No One Found',
    no_nearby_desc = 'There appears to be no one around',
    invalid_entry = 'Invalid Entry',
    invalid_entry_desc = 'Please enter a valid number',
    fines = 'Fines',
    fines_desc = 'Issue a nearby player a fine',
    search_player = 'Search Suspect',
    search_player_desc = 'Search a nearby suspect',
    jail_player = 'Jail Suspect',
    jail_player_desc = 'Jail a nearby suspect',
    minutes_dialog = 'Sentencing',
    minutes_dialog_field = 'Months',
    escort_player = 'Escort Suspect',
    escort_player_desc = 'Escort a nearby suspect',
    handcuff_hard_player = 'Handcuff Suspect (hard)',
    handcuff_hard_player_desc = 'Handcuff a nearby suspect (hard)',
    handcuff_soft_player = 'Handcuff Suspect (soft)',
    handcuff_soft_player_desc = 'Handcuff a nearby suspect (soft)',
    put_in_vehicle = 'Place In Vehicle',
    put_in_vehicle_desc = 'Place nearby suspect in vehicle',
    check_id = 'Check Identification',
    check_id_desc = 'Check nearby suspect\'s I.D.',
    id_result_menu = 'Identification Results',
    name = 'Name',
    job = 'Job',
    job_position = 'Position',
    dob = 'Date Of Birth',
    sex = 'Gender',
    bac = 'BAC',
    licenses = 'Licenses',
    total_licenses = 'Total Licenses:',
    no_licenses = 'No Licenses',
    revoke_license = 'Revoke License',
    license_revoked = 'License Revoked',
    license_revoked_desc = 'You have successfully revoked license',
    armoury_menu = 'Armory Menu',
    take_out_vehicle = 'Remove From Vehicle',
    take_out_vehicle_desc = 'Remove suspect from vehicle',
    not_restrained = 'Target Unrestrained',
    not_restrained_desc = 'You must restrain the criminal before escorting them',
    vehicle_not_found = 'No Vehicle Found',
    vehicle_not_found_desc = 'No vehicle found nearby',
    unconcious = 'Person Unconcious',
    unconcious_desc = 'Person appears unconcious',
    police_garage = 'Garage',
    police = 'Police',
    plate = 'Plate Number',
    owner = 'Owner',
    possibly_stolen = 'Caution!',
    possibly_stolen_desc = 'Vehicle Possibly Stolen',
    vehicle_interactions = 'Vehicle Interactions',
    vehicle_interactions_desc = 'Inspect nearby vehicle',
    vehicle_information = 'Vehicle Information',
    vehicle_information_desc = 'Information on nearby vehicle',
    lockpick_vehicle = 'Lockpick Vehicle',
    locakpick_vehicle_desc = 'Force access to nearby vehicle',
    lockpick_progress = 'Lockpicking Vehicle . . .',
    too_far = 'Too Far Away',
    too_far_desc = 'The target vehicle is too far away',
    lockpicked = 'Successfully Unlocked',
    lockpicked_desc = 'You have successfully unlocked the target vehicle',
    cancelled = 'Cancelled',
    cancelled_desc = 'You cancelled your last action',
    impound_vehicle = 'Impound Vehicle',
    impound_vehicle_desc = 'Impound Nearby Vehicle',
    impounding_progress = 'Impounding Vehicle . . .',
    driver_in_car = 'Driver In Vehicle',
    driver_in_car_desc = 'Remove driver from vehicle prior to impounding!',
    car_impounded_desc = 'Vehicle has been impounded',
    place_object = 'Place Objects',
    place_object_desc = 'Place objects on the floor.',
    prop_help_text = 'Press ~INPUT_CONTEXT~ to move the object.\nPress ~INPUT_DETONATE~ to delete the object.',
    prop_help_text2 = 'Press ~INPUT_CONTEXT~ to place the object.',

    fine_sent = 'Fines Sent',
    fine_sent_desc = 'You have successfully sent fine for $%s!',
    fine_received = 'Fine Received',
    fine_received_desc = 'You have received a fine for $%s',
    male = 'Male',
    female = 'Female',
    mr = 'Mr.',
    mrs = 'Mrs.',
    debt_collection = 'Debt Collection',
    db_email =
    'Dear %s %s, <br /><br />The Central Judicial Collection Agency (CJCA) charged the fines you received from the police.<br />There is <strong>$%s</strong> withdrawn from your account.<br /><br />Kind regards,<br />Mr. Wasabi',

    spawn_blocked = 'Garage Blocked',
    spawn_blocked_desc = 'You can not pull your vehicle out because it is blocked!',


    --GSR New
    positive = 'Positive',
    positive_gsr_desc = 'The suspect has tested POSITIVE for gunshot residue!',
    negative = 'Negative',
    negative_gsr_desc = 'The suspect has tested NEGATIVE for gunshot residue!',
    gsr_test = 'GSR Test',
    gsr_test_desc = 'Test a nearby suspect for gunshot residue',
    hands_clean = 'Cleaned',
    hands_clean_desc = 'You have successfully cleaned your hands of gunshot residue!',
    gsr_wash_ui = '[E] - Wash Hands',

    -- Go on/off duty new
    on_duty = 'On Duty',
    on_duty_desc = 'You have just switched to on duty!',
    off_duty = 'Off Duty',
    off_duty_desc = 'You have just switched to off duty!',

    robbing_player = 'Robbing Victim. . .',

    cancelled_action = 'Cancelled Action',
    cancelled_action_desc = 'You\'re last action was cancelled!',

    no_cuffs = 'No Handcuffs',
    no_cuffs_desc = 'You do not have any handcuffs in your pockets!',
    failed = 'Failed',
    lockpick_handcuff_success = 'You have successfully lockpicked the handcuffs!',
    lockpick_handcuff_fail = 'You failed to lockpick the handcuffs!',
    lockpick_broke = 'Lockpick Bent',
    lockpick_broke_desc = 'Your lockpick has bent!',
    grant_license = 'Issue Weapon License',
    grant_license_desc = 'Issue a weapons license to a nearby person',
    player_id = 'Player ID:',
    select_player = 'Select Person',
    license_granted = 'License Awarded',
    license_granted_desc = 'You awarded a weapons license to %s (%s)',
    license_alr_granted = 'This person already has a license!',
    weapon_license = 'Weapon License',
    weapon_license_desc = 'You were just awarded your weapons license.',

    in_vehicle = 'In Vehicle',
    in_vehicle_desc = 'You can not arrest the suspect while in a vehicle!',

    grade_to_low = 'Grade to low',
    grade_to_low_desc = 'Your grade is to low for this action',
    invoice_amount = 'Invoice Amount',
    amount_invoice = 'Amount',
    reason_invoice = 'Reason',
    gov_billing = 'Government Debt Collection'
}
